### PR TITLE
Fixed batchInsert casting of double values according to locale

### LINKED ISSUE #6526: Typecasting in batchInsert
I'm trying to insert data in the table

``` php
        Yii::$app->db->createCommand()->batchInsert(
            self::DB_CITY_TABLE_NAME,
            ['id', 'name', 'region_id', 'latitude', 'longitude'],
            $cities
        )->execute();
```

`$cities` is array 

``` php
array (size=1012)
  1 => 
    array (size=5)
      0 => string '1' (length=1)
      1 => string 'Хмельницкий' (length=22)
      2 => int 1
      3 => string '49.416668' (length=9)
      4 => string '27.000000' (length=9)
  2 => 
    array (size=5)
      0 => string '2' (length=1)
      1 => string 'Каменец-Подольский' (length=35)
      2 => int 1
      3 => string '48.683334' (length=9)
      4 => string '26.583332' (length=9)
  3 => 
    array (size=5)
      0 => string '3' (length=1)
      1 => string 'Нетишин' (length=14)
      2 => int 1
      3 => string '50.346695' (length=9)
      4 => string '26.633587' (length=9)
```

DB column type is `DOUBLE NOT NULL`
And error is:

### PR DESCRIPTION
**Pull request by cebe**
fixes #6526

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #6526

### CODE REVIEW

**Review by dynasource — APPROVED** [review]

File: framework/db/QueryBuilder.php [hunk 1]
```diff
@@ -278,6 +278,9 @@ public function batchInsert($table, $columns, $rows)
                 }
                 if (is_string($value)) {
                     $value = $schema->quoteValue($value);
+                } elseif (is_float($value)) {
+                    // ensure type cast always has . as decimal separator in all locales
+                    $value = str_replace(',', '.', (string) $value);
```
Comment (samdark) [inline framework/db/QueryBuilder.php]: Are you sure there are no separators beside `.` and `,`? I'd try to get it from `LC_NUMERIC` instead of hardcoding...

Comment (cebe) [inline framework/db/QueryBuilder.php]: pretty sure :)

```php
<?php

// Usage: install all locales: https://packages.debian.org/stretch/locales-all
// apt-get install locales-all
// then run the script

$locales = `localectl list-locales`;
$locales = array_filter(explode("\n", $locales));

//print_r($locales);
//
foreach($locales as $locale) {
	setlocale(LC_NUMERIC, $locale);
	echo (string) 1234.5678;
	// echo " $locale ";
	echo "\n";
}
```
```
$ php locales.php | sort | uniq
1234,5678
1234.5678
1234�5678
```

`1234�5678` refers to [ps](https://en.wikipedia.org/wiki/Pashto)_[AF](https://en.wikipedia.org/wiki/Afghanistan) which looks like a bug in their locale data because the sign is the UTF-8 replacement character. https://unicode-table.com/en/FFFD/

Comment (samdark) [inline framework/db/QueryBuilder.php]: OK.

**Review by samdark — APPROVED** [review]

**Review by SilverFire — APPROVED** [review]
