### PR TITLE
Fixes #13707: Fixed `\yii\web\ErrorHandler` not setting correct respo…

### LINKED ISSUE #13707: In Default ErrorView render by `yii\web\ErrorAction` ，the `Yii::$app->response->statusCode` is not correct
### What steps will reproduce the problem?
use  `Composer` to initialize  a clean Yii2 advanced app template
in `frontend/views/site/error.php`   add the following line
```php
<?= Yii::$app->response->statusCode?>
```
then, navigate to `a none-existing Url Location` in Browser,such as `http://yaa-frontend.dev/xxx`

### What is the expected result?

the above PHP code added to   `frontend/views/site/error.php`    should output `404`

### What do you get instead?
the  above PHP code added to   `frontend/views/site/error.php`    just output `200`  in page content
 **_this is not correct_**

**Note:** HTTP code in Browser is 404, **_this is correct_**.
image

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | PHP 7.1
| Operating system | Ubuntu 16.04 LTS

### PR DESCRIPTION
**Pull request by samdark**
…nse code to response object before rendering error view

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes/no
| Fixed issues  | #13707

### CODE REVIEW

**Comment by samdark** [comment]
Right. Tests...

**Comment by ihipop** [comment]
@samdark  I‘m interested in  how to write this unit test
should this test  run against `ErrorAction` or `ErrorHandler` ?

if run against `ErrorHandler` should it right below?
```php
 public function testRenderException()
    {
        Yii::$app->getErrorHandler()->handleException(new NotFoundHttpException('this is a 404 error'))
        $this->assertEquals(404,Yii::$app->response->statusCode);
    }
```

**Comment by dynasource** [comment]
@ihipop, ideally you should run it as isolated a possible without Yii::$app against just `ErrorHandler`

**Review by dynasource — CHANGES_REQUESTED** [review]
unit test required

**Comment by ihipop** [comment]
@samdark

**Comment by samdark** [comment]
@ihipop in this case test is for `renderException()` method only. You've got that part right. The thing that is tricker is that your test would pass with both old and new code. What we should test here is that code is set before rendering an exception view.

**Comment by ihipop** [comment]
@samdark so,the `test` should be written against `ErrorAction` ?
I've no Idea  ：（

**Comment by samdark** [comment]
@dynasource unit test added.

File: framework/web/ErrorAction.php [hunk 1]
```diff
@@ -98,6 +98,13 @@ public function init()
      */
     public function run()
     {
+        $response = Yii::$app->getResponse();
+        if ($this->exception instanceof HttpException) {
```
Comment (samdark) [inline framework/web/ErrorAction.php]: Not sure this is actually needed...

Comment (SilverFire) [inline framework/web/ErrorAction.php]: It's fine IMO

**Review by SilverFire — APPROVED** [review]

File: framework/web/ErrorAction.php (hunk 1 above)
Comment (dynasource) [inline framework/web/ErrorAction.php]: why is this done twice in this PR?

Comment (samdark) [inline framework/web/ErrorAction.php]: Because in case of ErrorAction, there's a way to trigger it w/ exception without actually going through error handler.

Comment (dynasource) [inline framework/web/ErrorAction.php]: what about handling this in Response itself by passing the exception

Comment (samdark) [inline framework/web/ErrorAction.php]: Which exception?

Comment (dynasource) [inline framework/web/ErrorAction.php]: to fix the duplication of logic in:
* https://github.com/yiisoft/yii2/pull/13708/files#diff-f4cd9aa0a2255e5362d10b956fe70974R102
* https://github.com/yiisoft/yii2/pull/13708/files#diff-7a2fbae94c890a0d999b38f8a82fe81eR92

Comment (samdark) [inline framework/web/ErrorAction.php]: Yes. I know that. Check tests. In case of action, error handler isn't involved and it's public API so same could be done in real projects. That's why a safeguard.

**Review by dynasource — APPROVED** [review]
