### PR TITLE
Handle DB session callback custom fields before session closed

### LINKED ISSUE #9438: error saving sessions
hi all, im using the new version of the yii2 2.0.6 but i have this problem

i get this Error

[16-Aug-2015 19:18:46 UTC] PHP Fatal error:  Uncaught exception 'yii\base\ErrorException' with message 'Unknown: Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/tmp)' in Unknown:0
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'Unknown: Failed...', 'Unknown', 0, Array)
#1 {main}

  thrown in Unknown on line 0

and is because i use this configuration

``` php
'session' => [
            'class' => 'yii\web\DbSession',
            'readCallback' => function ($fields) {
                    return [
                        'expireDate' => Yii::$app->formatter->asDate($fields['expire']),
                    ];
                },
            'writeCallback' => function ($session) {
                    return [
                        'user_id' => Yii::$app->user->id,
                        'ip' => $_SERVER['REMOTE_ADDR'],
                        'is_trusted' => $session->get('is_trusted', false),
                        'controllerCurrent' => Yii::$app->requestedAction->controller->id,
                        'actionCurrent' => Yii::$app->requestedAction->id,
                        'pageCurrent' => Yii::$app->id,
                        'is_guest' => Yii::$app->user->isGuest
                    ];
                }
        ]
```

in the common.php

in the localhost work Perfectly but in the remote i get the error

any have idea how can solve this ?

### PR DESCRIPTION
**Pull request by lubosdz**
Attempt to fix #9438, #13740, #15037.
This fixes error `Unkown: Failed to write session data (user)`.
Explanation of cause [here](https://github.com/yiisoft/yii2/issues/9438#issuecomment-469625968).

Please review - perhaps somebody might get better idea how to populate fields before closing the session without corrupting the data integrity .. (e.g. if a session variable stored into session field changed between being populated and closing the session). Personally I am not happy with this commit, but so far haven't found better solution :-|

### CODE REVIEW

**Comment by samdark** [comment]
Doesn't seem to pass tests: https://travis-ci.org/yiisoft/yii2/jobs/501995713

**Comment by lubosdz** [comment]
This is really hard to fix without BC break. 
The implementation is faulty since the very beginning.

Method `MultiFieldSession::composeFields()` attempts to do two things at the same time - populate custom fields in custom session handler after session is closed (inactive). This results into permanent errors when somebody tries to read some variable from session into custom field, typically `user ID`.

I tried 3 attempts to move preparation of custom fields, but there is always some unit test failing. I could update unit tests but it might break backward compatibility if somebody used this *feature* to set custom session content. 

Any idea how to fix ? - either introduce minor BC break or leave faulty implementation ? :-)

Also - it there guide how to run locally all framework tests? Before pushing the change I would like to run specific tests locally.

**Comment by samdark** [comment]
The tests could be executed with `./vendor/bin/phpunit`. As the argument you may pass the name of the test class.

**Comment by samdark** [comment]
> if somebody used this feature to set custom session content

That is possible.

**Comment by lubosdz** [comment]
Fail on codeclimate `writeSession accesses the super-global variable $_SESSION` - it's used in many methods. 

Final fix works, but IMO modifying session data directly via callback should not be allowed, just like it's not possible for FileSession. Users mainly use custom writeCallback fields for tracking who's online or IDs-related stuff etc. It's kinda undocumented dirty feature specific only to DB session :-)

**Comment by samdark** [comment]
We may consider disallowing it for 3.0 (sessions will be handled differently there anyway).

File: framework/web/DbSession.php [hunk 1]
```diff
@@ -76,6 +76,10 @@ class DbSession extends MultiFieldSession
      */
     public $sessionTable = '{{%session}}';
 
+    /**
+    * @var array Session fields to be written into session table columns
```
Comment (samdark) [inline framework/web/DbSession.php]: Need `@since 2.0.17`.

File: framework/web/DbSession.php [hunk 2]
```diff
@@ -136,6 +140,18 @@ public function regenerateID($deleteOldSession = false)
         }
     }
 
+    /**
+     * Ends the current session and store session data.
+     */
+    public function close()
```
Comment (samdark) [inline framework/web/DbSession.php]: Need `@since 2.0.17`.

File: framework/web/DbSession.php [hunk 3]
```diff
@@ -169,14 +185,28 @@ public function writeSession($id, $data)
...
         try {
-            $fields = $this->composeFields($id, $data);
-            $fields = $this->typecastFields($fields);
-            $this->db->createCommand()->upsert($this->sessionTable, $fields)->execute();
+            // ensure backwards compatability (fixed #9438)
+            if($this->writeCallback && !$this->fields){
+                $this->fields = $this->composeFields();
+            }
+            // ensure data consistency
+            if(!isset($this->fields['data'])){
```
Comment (samdark) [inline framework/web/DbSession.php]: Code formatting is wrong.

1. Need spaces `if (`
2. Need spaces `) {`

Comment (samdark) [reply framework/web/DbSession.php]: 3. Need spaces `} else {`

**Review by samdark — CHANGES_REQUESTED** [review]
Looks good except minor things.

File: framework/web/DbSession.php (hunk 2 above)
Comment (lubosdz) [reply framework/web/DbSession.php]: Done

File: framework/web/MultiFieldSession.php [hunk 4]
```diff
@@ -89,30 +89,19 @@ public function getUseCustomStorage()
...
-            $fields = array_merge(
-                $fields,
-                call_user_func($this->writeCallback, $this)
-            );
-            if (!is_string($fields['data'])) {
-                $_SESSION = $fields['data'];
-                $fields['data'] = session_encode();
-            }
+        $fields = $this->writeCallback ? call_user_func($this->writeCallback, $this) : [];
+        if($id !== null){
```
Comment (samdark) [inline framework/web/MultiFieldSession.php]: Formatting here is wrong as well.

**Review by samdark — COMMENTED** [review]
Is it possible to add unit tests for it?

File: framework/web/MultiFieldSession.php (hunk 4 above)
Comment (lubosdz) [reply framework/web/MultiFieldSession.php]: Sorry, missed that one, now it's fixed.

**Comment by lubosdz** [comment]
Unit tests for sessions are already there:
https://github.com/yiisoft/yii2/blob/master/tests/framework/web/session/AbstractDbSessionTest.php#L136
There is no new feature to test.
Or what should be added?

**Comment by samdark** [comment]
A test that failed before these changes and isn't failing with these changes.

**Comment by lubosdz** [comment]
There was no failing test before this fix.
Travis was failing, because my fix was not compatible with original implementation.
Now the fix is backwards compatible so no failing tests now - just like before the fix.

**Comment by lubosdz** [comment]
OK, I think it would make sense to add test for new method `close()` with user ID pulled out from session - to ensure custom fields do not interfere with inactive session anymore.

**Comment by lubosdz** [comment]
Whooops .. I did not intent to merge anything, 
I just clicked Updated branch button .. and it merged. 
Please check if it's OK or squash commits, whatever needed .. 
sorry, I am not really familiar with github administration, I use gitlab or bitbucket.

**Comment by samdark** [comment]
It's fine to merge master into pull request branch. No issues with it.

File: framework/web/DbSession.php [hunk 5]
```diff
@@ -169,14 +187,28 @@ public function writeSession($id, $data)
...
         // https://secure.php.net/manual/en/function.session-set-save-handler.php#refsect1-function.session-set-save-handler-notes
         try {
-            $fields = $this->composeFields($id, $data);
-            $fields = $this->typecastFields($fields);
-            $this->db->createCommand()->upsert($this->sessionTable, $fields)->execute();
+            // ensure backwards compatability (fixed #9438)
+            if ($this->writeCallback && !$this->fields) {
+                $this->fields = $this->composeFields();
+            }
+            // ensure data consistency
```
Comment (samdark) [inline framework/web/DbSession.php]: Would you please elaborate what happens in this block?

File: tests/framework/web/session/AbstractDbSessionTest.php [hunk 6]
```diff
@@ -147,6 +148,35 @@ public function testWriteCustomField()
...
 
+    /**
+     * @depends testReadWrite
+     */
+    public function testWriteCustomFieldWithUserId()
+    {
+        $session = new DbSession();
+        $session->open();
+
+        $savedUserId = mt_rand(111, 999);
```
Comment (samdark) [inline tests/framework/web/session/AbstractDbSessionTest.php]: Is it necessary for it to be random?

File: framework/web/DbSession.php (hunk 5 above)
Comment (lubosdz) [reply framework/web/DbSession.php]: This is to ensure backwards compatibility & that unit tests won't fail.
Basically it forces populating custom fields on directly calling custom session handler `$session->writeSession()`.

Normally, custom fields are populated [just before closing the session](https://github.com/yiisoft/yii2/pull/17188/files#diff-6f6a191d70c6d117086ec1873e231af5R152).

But original unit tests would not call dedicated method `$session->close()` but instead directly custom handler method `$session->writeSession(sessId, sessDataString)` (because the session has not been opened), which IMO is not quite correct. 

I did not want to touch original unit tests, therefore this line must have been added as a work around solution. If direct injection of session data will drop in Yii3 these lines may be removed, or unit test should be rewritten to open/close session rather than directly calling custom handlers.

File: tests/framework/web/session/AbstractDbSessionTest.php (hunk 6 above)
Comment (lubosdz) [reply tests/framework/web/session/AbstractDbSessionTest.php]: No, it just did development for me slightly easier to check that test locally passed during debug. Shall I make it static, e.g. 123 ?

Comment (samdark) [reply tests/framework/web/session/AbstractDbSessionTest.php]: Keeping things simple is better. Yes.

Comment (lubosdz) [reply tests/framework/web/session/AbstractDbSessionTest.php]: OK, done.

**Review by samdark — APPROVED** [review]

**Review by sergeymakinen — APPROVED** [review]
LGTM. Hacky but should work.

**Comment by samdark** [comment]
Merged. Thank you!
