### PR TITLE
Closes #17057. MSSQL quoted tables.

### LINKED ISSUE #17057: Dots in the table names
### What steps will reproduce the problem?

Set up an active record for a table contains dots in the name (Yes, ms sqlserver table names can has a dots like this: [SRV_NAME].[DB_NAME].[SCHEMA_NAME].[TABLE.NAME.WITH.A.LOT.OF.DOTS.]). 

### What is the expected result?

Nothing too bad.

### What do you get instead?

Database Exception.

resolveTableNames method in yii\db\mssql\Schema treats every dot like qualifier delimiter.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |2.0.15.1
| PHP version      | 7.2
| Operating system |Win srv 2012 r2

### PR DESCRIPTION
**Pull request by alexkart**
Fix issues with table names that contain special characters or keywords in MSSQL.

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #17057

### CODE REVIEW

File: framework/db/Schema.php [hunk 1]
```diff
@@ -485,14 +484,24 @@ public function quoteTableName($name)
...
         foreach ($parts as $i => $part) {
             $parts[$i] = $this->quoteSimpleTableName($part);
         }
 
         return implode('.', $parts);
     }
 
+    /**
+     * Splits full table name into parts
+     * @param $name
```
Comment (samdark) [inline framework/db/Schema.php]:
```suggestion
     * @param string $name
```

File: framework/db/Schema.php [hunk 2]
```diff
@@ -485,14 +484,24 @@ public function quoteTableName($name)
...
+     * @return array
```
Comment (samdark) [inline framework/db/Schema.php]: Need `@since`.

File: framework/db/mssql/Schema.php [hunk 3]
```diff
@@ -126,6 +126,24 @@ protected function resolveTableName($name)
         return $resolvedName;
     }
 
+    /**
+     * {@inheritDoc}
+     * @param $name
```
Comment (samdark) [inline framework/db/mssql/Schema.php]:
```suggestion
     * @param string $name
```

File: framework/db/mssql/Schema.php [hunk 4]
```diff
@@ -126,6 +126,24 @@ protected function resolveTableName($name)
...
+     * @return array|mixed
```
Comment (samdark) [inline framework/db/mssql/Schema.php]: Why would it return mixed?

File: framework/db/mssql/Schema.php [hunk 5]
```diff
@@ -126,6 +126,24 @@ protected function resolveTableName($name)
...
+     */
+    protected function getTableNameParts($name)
+    {
+        $parts = [$name];
+        preg_match_all('/([^.\[\]]+)|\[([^\[\]]+)\]/', $name, $matches);
+        if (isset($matches[0]) && is_array($matches[0]) && !empty($matches[0])) {
+            $parts = $matches[0];
+        }
+
+        $parts = str_replace(['[', ']'], '', $parts);
```
Comment (samdark) [inline framework/db/mssql/Schema.php]: If the `if` above we assume that `$parts` is an array. Then we're doing `str_replace` on it. That would cause error.

**Review by samdark — CHANGES_REQUESTED** [review]

File: framework/db/mssql/Schema.php (hunk 5 above)
Comment (alexkart) [reply framework/db/mssql/Schema.php]: Why? `str_replace` works with arrays.

Comment (samdark) [reply framework/db/mssql/Schema.php]: You're right. PHP standard library is a mess :)

File: framework/db/mssql/Schema.php [hunk 6]
```diff
@@ -126,6 +126,24 @@ protected function resolveTableName($name)
         return $resolvedName;
     }
 
+    /**
+     * {@inheritDoc}
+     * @param $name string
+     * @return array
+     */
+    protected function getTableNameParts($name)
```
Comment (samdark) [inline framework/db/mssql/Schema.php]: Need `@since`.

**Review by samdark — APPROVED** [review]
Other than missing `@since` tag it's all good. Great job!

File: framework/db/Schema.php [hunk 7]
```diff
@@ -494,8 +494,9 @@ public function quoteTableName($name)
 
     /**
      * Splits full table name into parts
-     * @param $name
+     * @param $name string
```
Comment (Thoulah) [inline framework/db/Schema.php]: `@param string $name`
https://docs.phpdoc.org/references/phpdoc/tags/param.html

File: framework/db/mssql/Schema.php [hunk 8]
```diff
@@ -128,8 +128,8 @@ protected function resolveTableName($name)
 
     /**
      * {@inheritDoc}
-     * @param $name
-     * @return array|mixed
+     * @param $name string
```
Comment (Thoulah) [inline framework/db/mssql/Schema.php]: `@param string $name`

**Comment by samdark** [comment]
Merged. Thank you!

**Comment by alexkart** [comment]
@samdark are `framework/db/mssql/` tests run on CI? I've found one more place where we need to handle table names with dots. But this case should be caught by this test `framework\db\mssql\SchemaTest:testGetTableSchemas`.

**Comment by samdark** [comment]
I think they currently aren't run.

**Comment by alexkart** [comment]
> I think they currently aren't run.

I see. BTW, there are lots of broken MSSQL tests.

**Comment by samdark** [comment]
Yes :( If you have ideas on how to run these via travis, let me know.

**Comment by alexkart** [comment]
Something like this? https://github.com/biolab/orange3/commit/ea8205a20acd6a74dfd7c829abed7f0bd00c7184

**Comment by samdark** [comment]
Yes, that could work. Does travis allow running non-docker and docker in the same build?
