### PR TITLE
Fixes #13738: getQueryParams() method in yii.js fails on URL with question mark and no query parameters

### LINKED ISSUE #13738: getQueryParams() method in yii.js fails on URL with question mark and no query parameters
### What steps will reproduce the problem?

1. Make GridView with filter in column
2. Enter some text, press Enter

### What is the expected result?

Filter must work without JS errors

### What do you get instead?

Filter not work.

In Console i see error "Uncaught TypeError: Cannot read property 'replace' of undefined"
image

This error appeared after this commit https://github.com/yiisoft/yii2/commit/17df7577a53ee2ac35d8e53ed87aaf03ce9309ac#diff-f433792b516845f488519deb1a72741aR293

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      |
| Operating system |

### PR DESCRIPTION
**Pull request by vlydev**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #13738

### CODE REVIEW

**Comment by vladdnepr** [comment]
@arogachev tests for JS?

**Comment by samdark** [comment]
Yes: https://github.com/yiisoft/yii2/tree/master/tests/js/tests

**Comment by vladdnepr** [comment]
@samdark Cool. I didnt notice. Already added.

File: framework/assets/yii.js [hunk 1]
```diff
@@ -279,10 +279,10 @@ window.yii = (function ($) {
             for (var i = 0, len = pairs.length; i < len; i++) {
                 var pair = pairs[i].split('=');
                 var name = decodeURIComponent(pair[0].replace(/\+/g, '%20'));
-                var value = decodeURIComponent(pair[1].replace(/\+/g, '%20'));
                 if (!name.length) {
                     continue;
                 }
+                var value = decodeURIComponent(pair[1].replace(/\+/g, '%20'));
```
Comment (arogachev) [inline framework/assets/yii.js]: I think this should be fixed differently. In error case we have an array with one element - empty string - `[""]`. It's better to check and remove it from array before the loop (or construct array in a way that prevents it) so it will not be considered as pair at all. We don't have any name - value pairs with url `/posts/index?`, I think it's more correct.

File: tests/js/tests/yii.test.js [hunk 2]
```diff
@@ -739,6 +739,7 @@ describe('yii', function () {
     describe('getQueryParams method', function () {
         withData({
             'no query parameters': ['/posts/index', {}],
+            'no query parameters with question char': ['/posts/index?', {}],
```
Comment (arogachev) [inline tests/js/tests/yii.test.js]: Ideally this needs to be tested for `yii.gridView.js` too. See https://github.com/yiisoft/yii2/blob/9fa66b23a53e8268b1808977146056b92ac60a8a/tests/js/tests/yii.gridView.test.js#L305.

**Review by arogachev — CHANGES_REQUESTED** [review]

**Comment by arogachev** [comment]
Also according CHANGELOG line is required.

**Comment by vladdnepr** [comment]
@arogachev All requested changes are made

File: framework/assets/yii.js [hunk 3]
```diff
@@ -273,7 +273,7 @@ window.yii = (function ($) {
                 return {};
             }
 
-            var pairs = url.substring(pos + 1).split('#')[0].split('&'),
+            var pairs = url.substring(pos + 1).split('#')[0].split('&').filter(String),
```
Comment (arogachev) [inline framework/assets/yii.js]: First of all, thanks for the made improvements. Here are some remarks however:

1) In `pairs` array we already have strings only so I feel that repeated string conversion is redundant. Something more explicit like:

```js
var pairs = url.substring(pos + 1).split('#')[0].split('&').filter(function (value) {
    return value !== '';
})
```

would be better IMO.

2) Used [Array.prototype.filter](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) method is OK, but:

>`filter()` was added to the ECMA-262 standard in the 5th edition; as such it may not be present in all implementations of the standard.

To be more specific, it's not supported in Internet Explorer 8 and I'm not sure that we can just refuse supporting it (there is a small chance that this requirement takes place to be in someone's project based on Yii2). I don't think that polyfill will be a good option neither, because its usage currently will be limited by this code only and it seems like an overhead. Regular loop can solve the problem, or maybe consider an option to try not include such values initially to avoid additional filter loop.

@samdark Please remind, do we support Internet Explorer 8?

**Review by arogachev — CHANGES_REQUESTED** [review]

File: framework/assets/yii.js (hunk 3 above)
Comment (samdark) [inline framework/assets/yii.js]: If it could be easily replaced with something compatible with earlier standards, it's better to use more compatible solution. If there's no easy replacement, let it be as is.

Comment (vladdnepr) [inline framework/assets/yii.js]: @arogachev OK. I made filtering by jQuery grep

**Comment by vladdnepr** [comment]
@arogachev OK. I made filtering by jQuery grep

**Comment by arogachev** [comment]
I've made some corrections. You can find out what was wrong from according commits. Now IMO it's ready for merge.

@samdark We should use our Github nicknames in CHANGELOG, shouldn't we?

**Review by arogachev — APPROVED** [review]

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
> @samdark We should use our Github nicknames in CHANGELOG, shouldn't we?

Yes. It's easier to find a person who did the change this way.

**Comment by samdark** [comment]
Merged. Thanks!
