### PR TITLE
fixed string helper encoding when Yii::$app is not available

### LINKED ISSUE #13254: StringValidator crashes if \Yii::$app is not set.
### What steps will reproduce the problem?
Create a `StringValidator` instance without having `Yii::$app` set.

### What is the expected result?
String validation should work fine without an app.

### What do you get instead?
Exception `trying to get property of non-object`.

### Additional info
The cause is:
````
if ($this->encoding === null) {
    $this->encoding = Yii::$app->charset;
}
````

I think it would be nice if there was a check to see if `Yii::$app` is set.

| Q                | A
| ---------------- | ---
| Yii version      | latest
| PHP version      | N/A
| Operating system | N/A

### PR DESCRIPTION
**Pull request by cebe**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | let travis decide on this one
| Fixed issues  | #13254

fixes #13254

### CODE REVIEW

**Comment by klimov-paul** [comment]
See https://github.com/yiisoft/yii2/issues/13254#issuecomment-268750069

We should either fix all the dependencies on Yii application around the helper classes and validators or leave everything be as it is.
Why should we fix `StringValidator` to work without an application instance, while leaving `FileHelper` depending on it?

**Comment by alexraputa** [comment]
> We should either fix all the dependencies on Yii application around the helper classes and validators or leave everything be as it is.

Sounds good. This would make development more flexible.

**Comment by dynasource** [comment]
IMO all dependencies on an active Yii application should be minimized in the helpers. For three reasons:
* Static behavior: Helpers are static and focussed on processing instead of depending on global state. You are expecting loosely tied helper methods
* Testing: enough scenarios are thinkable in a PHP unit environment in which you are testing something in which you don't need an Application to be active
* Use of Yii helpers in non Yii applications

File: framework/helpers/BaseStringHelper.php [hunk 1]
```diff
@@ -104,12 +104,15 @@ public static function dirname($path)
      */
     public static function truncate($string, $length, $suffix = '...', $encoding = null, $asHtml = false)
     {
+        if ($encoding === null) {
+            $encoding = Yii::$app ? Yii::$app->charset : 'UTF-8';
```
Comment (dynasource) [inline framework/helpers/BaseStringHelper.php]: shouldnt this be put once in an ApplicationHelper?

Comment (Faryshta) [inline framework/helpers/BaseStringHelper.php]: or `Yii::encoding()`.

Comment (cebe) [inline framework/helpers/BaseStringHelper.php]: what exactly and why?

Comment (cebe) [inline framework/helpers/BaseStringHelper.php]: A helper to replace a simple ternary operator check?

**Review by samdark — APPROVED** [review]

File: framework/helpers/BaseStringHelper.php (hunk 1 above)
Comment (Faryshta) [inline framework/helpers/BaseStringHelper.php]: I don't think a **new** helper can be needed but that ternary operator seem to happen a lot. How about a new method?

`StringHelper::getEncoding()` or `Yii::encoding()`

Comment (cebe) [inline framework/helpers/BaseStringHelper.php]: Even though it is happening often that still does not justify an extra method call. Besides degrading performance it makes the code depend on more things and harder to read.

**Comment by cebe** [comment]
rebased and made sure tests cover it by forcing Yii::$app to be null in test cases. This should be done for more helpers, will prepare a separate PR for that.

File: framework/helpers/BaseStringHelper.php (hunk 1 above)
Comment (Faryshta) [inline framework/helpers/BaseStringHelper.php]: >  harder to read

```php
$encoding = Yii::$app ? Yii::$app->charset : 'UTF-8';
// vs
$encoding = self::getEncoding();
```

I think the second case is easier to read.

> degrading performance

Microseconds degrading performance. I don't thinkthats an argument.

> Even though it is happening often that still does not justify an extra method call

If you want to stay DRY yes thats a great justification.

and that method can be used on other places such as widgets or views.

Comment (klimov-paul) [inline framework/helpers/BaseStringHelper.php]: Usage of ternary operator introduces a "magic string" - `UTF-8`.
Keeping default encoding at Application field is a one thing, but put putting same string constant all over the code is a different one.
While in current state `UTF-8` is covering most of the needs and is de-facto standard it may change in the future. After several years we may use `UTF-16` for example.

We should either introduce a static level for default encoding (e.g. `Yii::$encoding` or `Yii::encoding()` or `Yii::$defaultEncoding`) or abandon the whole idea.

**Review by klimov-paul — CHANGES_REQUESTED** [review]

File: framework/helpers/BaseStringHelper.php (hunk 1 above)
Comment (cebe) [inline framework/helpers/BaseStringHelper.php]: > We should either introduce a static level for default encoding 

isn't that the job of Yii::$app->charset? It is default to `'UTF-8'` if you configure your application and change it you get a different encoding. Ternary check only makes the default value available if app is not configured.

Comment (klimov-paul) [inline framework/helpers/BaseStringHelper.php]: > isn't that the job of Yii::$app->charset?

Yes it is - this is a job, which makes `Application` instance to be essential for the helper running.

>Ternary check only makes the default value available if app is not configured.

You are introducig magick constant with it, which should never be present in the code.
Standalone valdator and helper running will become impossible in case you need default encoding different from `UTF-8`.

Comment (samdark) [inline framework/helpers/BaseStringHelper.php]: I'd introduce a static property in the class itself for the purpose.

Comment (cebe) [inline framework/helpers/BaseStringHelper.php]: > Standalone valdator and helper running will become impossible in case you need default encoding different from UTF-8.

For the helper it is no problem as long as you specify the `$encoding` param of the method.
For the validator we could add a property that defaults to `Yii::$app->charset` or 'UTF-8' if not set.

Comment (klimov-paul) [inline framework/helpers/BaseStringHelper.php]: > For the helper it is no problem as long as you specify the $encoding param of the method.

You can do it now, with current code, and thus avoid coupling with `Application`. Following such argument - no change is needed at all.

Comment (dynasource) [inline framework/helpers/BaseStringHelper.php]: Yii::$app should ideally be removed out of this helper

Comment (rob006) [reply framework/helpers/BaseStringHelper.php]: I'm for `Yii::ENCODING` constant or just leaving `UTF-8` string in ternary check. This approach is already used in multiple places in core. Symfony uses `UTF-8` as "magic string", and Laravel don't even care about different encodings and have hardcoded `UTF-8` in multiple places. It is not worth complicating this only for extremely edge cases.

Comment (samdark) [reply framework/helpers/BaseStringHelper.php]: Leaving a string there sounds OK to me.

File: framework/helpers/BaseStringHelper.php [hunk 2]
```diff
@@ -104,12 +104,17 @@ public static function dirname($path)
...
-            return static::truncateHtml($string, $length, $suffix, $encoding ?: Yii::$app->charset);
+            return static::truncateHtml($string, $length, $suffix, $encoding);
         }
 
-        if (mb_strlen($string, $encoding ?: Yii::$app->charset) > $length) {
-            return rtrim(mb_substr($string, 0, $length, $encoding ?: Yii::$app->charset)) . $suffix;
+        if (mb_strlen($string, $encoding) > $length) {
+            return rtrim(mb_substr($string, 0, $length, $encoding)) . $suffix;
+        } else {
+            return $string;
```
Comment (tom--) [inline framework/helpers/BaseStringHelper.php]: What do the above two lines do?

**Comment by tom--** [comment]
When there is no framework "global context" (Yii::$app) where the default or user configuration can go, I would expect the framework to get out of the way rather than force any hardcoded value. Instead, I would expect PHP's INI directive [default_charset](https://secure.php.net/manual/en/ini.core.php#ini.default-charset) to apply.

File: framework/helpers/BaseStringHelper.php (hunk 2 above)
Comment (samdark) [reply framework/helpers/BaseStringHelper.php]: If string length is more than limit defined in `$length` it trims it to the length specified, then adding `$suffix`.

**Comment by samdark** [comment]
Could be a good idea. @cebe what do you think?

**Comment by cebe** [comment]
default_charset is PHP 5.6.0, so that would be the way to go in 2.1.

File: framework/helpers/BaseStringHelper.php (hunk 2 above)
Comment (tom--) [reply framework/helpers/BaseStringHelper.php]: It's the two new lines

```
} else {
    return $string;
```

that i think need explanation. The next line after the `else {}` is `return $string;`

**Comment by sergeymakinen** [comment]
As we discuss a _framework_ helper, I'd like to implement both @tom-- & @klimov-paul ideas: `StringHelper::encoding()` which returns `Yii::$app->charset` / `ini_get('default_charset')` / `'UTF-8'` depending on a context and I'm fine with it.

File: tests/framework/helpers/StringHelperTest.php [hunk 3]
```diff
@@ -19,7 +19,9 @@ class StringHelperTest extends TestCase
     protected function setUp()
     {
         parent::setUp();
-        $this->mockApplication();
+
+        // destroy application, Helper must work without Yii::$app
+        $this->destroyApplication();
```
Comment (dynasource) [inline tests/framework/helpers/StringHelperTest.php]: shouldnt we extend from a PhpUnit base class in which no application is setup?

**Comment by dynasource** [comment]
I agree. The encoding logic should be taken out.

File: tests/framework/helpers/StringHelperTest.php (hunk 3 above)
Comment (rob006) [reply tests/framework/helpers/StringHelperTest.php]: @dynasource `yiiunit\TestCase` dose not mock application by default. `destroyApplication()` is used only to make sure that `Yii::$app` is not setup as leftovers after previous tests.

**Review by rob006 — APPROVED** [review]
I'm for merging this as is. `Yii::encoding()` could be added in another PR, there is no sense to block this one.

**Comment by samdark** [comment]
Merged. Thanks @cebe for working on it and everyone for reviews and suggestions.
