### PR TITLE
Fix #18406 - avoid PDOExceptions when working with autocommitted transactions

### LINKED ISSUE #18406: PHP 8 - "There is no active transaction" when transaction is autocommitted
As of PHP 8, `PDO::commit()` and `rollBack()` will throw a `There is no active transaction` PDOException if the transaction had been autocommitted, as MySQL will do whenever a schema change is made. Previously they would fail silently.

The change was made in this commit: https://github.com/php/php-src/commit/990bb34891c83d12c5129fd781893704f948f2f4

### What steps will reproduce the problem?

1. Connect to a MySQL database
2. Call `Yii::$app->db->beginTransaction()`
3. Make a schema change, such as add a new column to a table (the transaction will be autocommitted in the process)
4. Call `Yii::$app->db->commit()`

### What is the expected result?

PHP would move along to the next line of code, regardless of whether the app is running on PHP 5, 7, or 8.

_(Note: it could be argued that an exception should in fact be thrown here in Yii 3, but I think it’s best to avoid a BC break in Yii 2.)_

### What do you get instead?

A PDOException is thrown with the message `There is no active transaction` when running PHP 8.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.39.3
| PHP version      | 8.0.0RC3
| Operating system | Ubuntu 20.04.1 LTS

### PR DESCRIPTION
**Pull request by brandonkelly**
This fixes #18406 by checking if there is an active transaction before committing/rolling back transactions.

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #18406

### CODE REVIEW

**Comment by samdark** [comment]
Looks alright. Is it possible to cover it with a unit test?

**Review by bizley — APPROVED** [review]

**Comment by brandonkelly** [comment]
@samdark Sure, just added one. I put it in `yiiunit\framework\db\mysql\ConnectionTest` since it’s a MySQL-specific bug, but can move to `yiiunit\framework\db\ConnectionTest` if you’d prefer that.

File: tests/framework/db/mysql/ConnectionTest.php [hunk 1]
```diff
@@ -7,11 +7,27 @@
...
+
 /**
  * @group db
  * @group mysql
  */
 class ConnectionTest extends \yiiunit\framework\db\ConnectionTest
 {
     protected $driverName = 'mysql';
+
+    public function testTransactionAutocommit()
```
Comment (bizley) [inline tests/framework/db/mysql/ConnectionTest.php:20]:
```suggestion
    /**
     * @doesNotPerformAssertions
     */
    public function testTransactionAutocommit()
```

**Review by bizley — CHANGES_REQUESTED** [review]

File: framework/db/Transaction.php [hunk 2]
```diff
@@ -161,15 +164,21 @@ public function commit()
         $this->_level--;
         if ($this->_level === 0) {
             Yii::debug('Commit transaction', __METHOD__);
-            $this->db->pdo->commit();
+            // make sure the transaction wasn't autocommitted
+            if ($this->db->pdo->inTransaction()) {
```
Comment (githubjeka) [inline framework/db/Transaction.php:168]: You have muted a bug of the function above IMHO.
```php
if (!$this->getIsActive()) {
    throw new Exception('Failed to commit transaction: transaction was inactive.');
}
```

**Review by githubjeka — CHANGES_REQUESTED** [review]
Should be studied in more detail

File: framework/db/Transaction.php (hunk 2 above)
Comment (bizley) [reply framework/db/Transaction.php:168]: Right, I was too hasty with accepting this. Is there a significant difference now between `$this->getIsActive()` and `$this->db->pdo->inTransaction()`?

Comment (brandonkelly) [reply framework/db/Transaction.php:168]: @githubjeka As mentioned in #18406, I think it’s worth changing this behavior for Yii 3, but the point here is to avoid breaking backwards compatibility.

@bizley `getIsActive()` is only concerned with the internal record of the transaction, but is unaware of whether the transaction is actually still active, which isn’t the case if you’re running MySQL and the transaction had been [implicitly committed due to a schema change](https://dev.mysql.com/doc/refman/8.0/en/implicit-commit.html).

Comment (bizley) [reply framework/db/Transaction.php:168]: I'm wondering if this check could be placed in `$this->getIsActive()`.

Comment (samdark) [reply framework/db/Transaction.php:168]: Placing the check in `$this->getIsActive()` is an interesting idea. May work well. @brandonkelly what do you think?

Comment (githubjeka) [reply framework/db/Transaction.php:168]: When you placing the check in `$this->getIsActive()` you should handle `Exception('Failed to commit transaction: transaction was inactive.');`

and add this code to the client algoritm 

```
Connect to a MySQL database
Call Yii::$app->db->beginTransaction()
Make a schema change, such as add a new column to a table (the transaction will be autocommitted in the process)
catch()
Call Yii::$app->db->commit()
```

It makes me sad

Comment (brandonkelly) [reply framework/db/Transaction.php:168]: Placing it there might be a good idea for Yii 3, but would be a BC break in the meantime, since `commit()` and `rollBack()` will each throw an exception if that returns `false`. So all it would change (versus doing nothing) is that `commit()` and `rollBack()` would start returning `yii\db\Exception`s rather than `PDOException`s.

Comment (bizley) [reply framework/db/Transaction.php:168]: `rollBack()` just returns nothing, only `commit()` would throw exception. And while I'm going through the code for me it looks like `getIsActive()` was never a good indicator whether the transaction is active (just checking a level and whether the PDO instance is set), it should always use `PDO::inTransaction()` as well). IMO the current code is bad and what @brandonkelly proposes should be placed in `getIsActive()` with upgrade info stating the users depending on previous code must update their apps, because simply ignoring autocommit was a bug. If the new check goes to `getIsActive()` it fixes also `setIsolationLevel()` because transaction must be active there as well.

Comment (brandonkelly) [reply framework/db/Transaction.php:168]: I completely agree that this PR isn’t great, but any other change would be significantly more involved, and would introduce a breaking change.

This is the situation:

- yii\db\Transaction has always (ignorantly) assumed that it is the authority on whether a transaction is currently active, and at what “level”.
- That has never been accurate with MySQL, due to implicit commits that Yii was unaware of
- A change to that behavior is going to lead to lots of code breakage

I’m simply saying that **for now**, ignorance is bliss, and Yii should just look the other way when it turns out the transaction isn’t _actually_ active even though its record states that it is.

Comment (bizley) [reply framework/db/Transaction.php:168]: Well, all you said is true. @samdark make a call please.

Comment (samdark) [reply framework/db/Transaction.php:168]: I think, current solution for Yii 2, `getIsActive()` for Yii 3 AR.

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
👍
