### PR TITLE
Fixed #18160, #18192: Fixed `registerFile` with argument depends set …

### LINKED ISSUE #18160: Current behavior is like that on purpose and there's a test for it in `ViewTest.php`:
Current behavior is like that on purpose and there's a test for it in `ViewTest.php`:

```php
// The timestamp setting won't be redefined because global AssetManager is used
$view = new View();
$view->registerJsFile('/assetSources/js/jquery.js', [
    'appendTimestamp' => true,
    'depends' => 'yii\web\AssetBundle',
]); // <script src="/assetSources/js/jquery.js"></script>
$html = $view->render('@yiiunit/data/views/layout.php', ['content' => 'content']);
$this->assertNotRegExp($pattern, $html);
```

Similar for CSS.

The reasoning was that while script itself changes, dependencies are likely static and to be cached. That's why options of individual script / CSS aren't propagated and instead use either config of the asset bundle itself or asset manager config.

Thank you for contributing but won't merge the pull request:

1. The behavior is correct one for some valid cases.
2. It is configurable.
3. It's covered by tests so changing it is a backwards compatibility break for the functionality developers may rely on.

_Originally posted by @samdark in https://github.com/yiisoft/yii2/pull/18068#issuecomment-653251537_

### PR DESCRIPTION
**Pull request by Baleen-Y**
…does not use the position and appendTimestamp argument, also modify the unit view (baleeny)

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #18160, #18192

### CODE REVIEW

**Comment by bizley** [comment]
Some tests are failing.

**Comment by Baleen-Y** [comment]
> Some tests are failing.

I made some changes and it has now passed.

File: framework/web/AssetManager.php [hunk 1]
```diff
@@ -317,10 +317,6 @@ public function getAssetUrl($bundle, $asset)
             return $asset;
         }
 
-        if ($this->appendTimestamp && ($timestamp = @filemtime("$basePath/$asset")) > 0) {
```
Comment (bizley) [inline framework/web/AssetManager.php:320]: `appendTimestamp` is not used anymore? It's breaking BC then. Something is wrong here.

File: framework/web/View.php [hunk 2]
```diff
@@ -504,7 +505,7 @@ private function registerFile($type, $url, $options = [], $key = null)
                 'class' => AssetBundle::className(),
                 'baseUrl' => '',
                 'basePath' => '@webroot',
-                (string)$type => [!Url::isRelative($url) ? $url : ltrim($url, '/')],
+                (string)$type => [ArrayHelper::merge([!Url::isRelative($url) ? $url : ltrim($url, '/')], $originalOptions)],
```
Comment (bizley) [inline framework/web/View.php:508]: Should it be wrapped in array?

File: framework/web/AssetManager.php (hunk 1 above)
Comment (bizley) [reply framework/web/AssetManager.php:320]: Ok, but component should not have properties used only by other components. This needs to be refactored. And, if accepted, this is BC break, so old property should stay here with deprecation notice. @samdark do you agree?

File: framework/web/View.php (hunk 2 above)
Comment (bizley) [reply framework/web/View.php:508]: What I mean is that the output will be `[[...]]` instead of `[...]` - is it the way you want it? Also while you are at it, could you correct the old `$asssetManagerAppendTimestamp` name (few lines above)? It should only have 2 `s` ;)

File: framework/web/AssetManager.php (hunk 1 above)
Comment (Baleen-Y) [reply framework/web/AssetManager.php:320]: @bizley Code refactored. You can see if it is suitable. There are two new codeclimates issues. `$asssetManagerAppendTimestamp` has been modified.

File: framework/web/AssetManager.php [hunk 3]
```diff
@@ -625,4 +609,31 @@ protected function hash($path)
         $path = (is_file($path) ? dirname($path) : $path) . filemtime($path);
         return sprintf('%x', crc32($path . Yii::getVersion() . '|' . $this->linkAssets));
     }
+    /**
```
Comment (bizley) [inline framework/web/AssetManager.php:612]: Add line break before this line.

File: framework/web/AssetManager.php [hunk 4]
```diff
@@ -625,4 +609,31 @@ protected function hash($path)
...
+     * Returns the actual URL for the specified asset. Without parameters.
+     * The actual URL is obtained by prepending either [[AssetBundle::$baseUrl]] or [[AssetManager::$baseUrl]] to the given asset path.
+     * @param AssetBundle $bundle the asset bundle which the asset file belongs to
+     * @param string $asset the asset path. This should be one of the assets listed in [[AssetBundle::$js]] or [[AssetBundle::$css]].
+     * @return string the actual URL for the specified asset.
```
Comment (bizley) [inline framework/web/AssetManager.php:617]: Add `@since 2.0.39`

File: tests/framework/web/ViewTest.php [hunk 5]
```diff
@@ -414,15 +414,15 @@ public function testAppendTimestampForRegisterCssFile()
...
         $this->assertRegExp($pattern, $html);
 
-        // The timestamp setting won't be redefined because global AssetManager is used
+        // redefine AssetManager timestamp setting
         $view = new View();
         $view->registerCssFile('/assetSources/css/stub.css',
             [
                 'appendTimestamp' => true,
                 'depends' => 'yii\web\AssetBundle',
             ]); // <link href="/assetSources/css/stub.css" rel="stylesheet" >
```
Comment (bizley) [inline tests/framework/web/ViewTest.php:423]:
```suggestion
            ]); // <link href="/assetSources/css/stub.css?v=1601802758" rel="stylesheet" >
```

**Review by bizley — CHANGES_REQUESTED** [review]
Few things to polish, rest LGTM

File: tests/framework/web/ViewTest.php (hunk 5 above)
Comment (Baleen-Y) [reply tests/framework/web/ViewTest.php]: @bizley Thanks for your advice!

**Review by bizley — APPROVED** [review]

**Comment by samdark** [comment]
Thank you!
