### PR TITLE
Fix statcache in FileCache

### LINKED ISSUE #20300: Resetting after fileCache expires cannot immediately obtain values
### What steps will reproduce the problem?

```php
$rs = Yii::$app->cache->set('k', 'v', 5);
var_dump($rs);
var_dump(Yii::$app->cache->get('k'));
```

### What is the expected result?

bool(true)
string(1) "v"

### What do you get instead?

bool(true)
bool(false)

### Additional info

The first execution returned no problem. When k was reexecuted after 5 seconds expired, the returned result was wrong and I couldn't get the value immediately.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.50
| PHP version      | 8.1.27
| Operating system | openEuler

### PR DESCRIPTION
**Pull request by rob006**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  |  #20300

fix  #20300

### CODE REVIEW

**Review by terabytesoftw — APPROVED** [review]

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Thank you!

File: framework/caching/FileCache.php [hunk 1]
```diff
@@ -155,7 +155,12 @@ protected function setValue($key, $value, $duration)
                 $duration = 31536000; // 1 year
             }
 
-            return @touch($cacheFile, $duration + time());
+            if (@touch($cacheFile, $duration + time())) {
+                clearstatcache();
```
Comment (samdark) [inline framework/caching/FileCache.php:159]: We've ported it Yii3 cache and while doing so, decided that it's better to clear cache for that file only via `clearstatcache(false, $cacheFile)`. Does that make sense to you?

Comment (rob006) [reply framework/caching/FileCache.php:159]: Stat cache is stored only for one (last) file, so I don't think you need to specify file path here. It is only used if you want to clear realpath cache, which is no needed here. So I don't think these changes make any sense.
