### PR TITLE
Closes #17395 actions with underscores

### LINKED ISSUE #17395: Console list command error while using undersore in action name
### What steps will reproduce the problem?

Any controller in console namespace with action name like

```php
public function actionTest_01(){
// any code
}
```

So, using the underscore in the action name triggers the PHP Notice, without the underscore it is ok. Please note, that the underscores are officialy useable in the naming convention (https://subscription.packtpub.com/book/web_development/9781785287411/1/ch01lvl1sec12/naming-convention). 

### What is the expected result?

After using php yii or ./yii we should see the possible functions list under

"The following commands are available:"

### What do you get instead?

The error appears, like so:

- odbc-report                                               Class OdbcReportController
    odbc-report/build-reporting-03PHP Notice 'yii\base\ErrorException' with message 'Trying to get property 'id' of non-object'

in /Applications/MAMP/htdocs/site/vendor/yiisoft/yii2/console/Controller.php:601

Stack trace:
#0 /Applications/MAMP/htdocs/site/vendor/yiisoft/yii2/console/Controller.php(601): yii\base\ErrorHandler->handleError(8, 'Trying to get p...', '/Applications/M...', 601, Array)
#1 /Applications/MAMP/htdocs/site/vendor/yiisoft/yii2/console/Controller.php(456): yii\console\Controller->getActionMethodReflection(NULL)
#2 /Applications/MAMP/htdocs/site/vendor/yiisoft/yii2/console/controllers/HelpController.php(339): yii\console\Controller->getActionHelpSummary(NULL)
#3 /Applications/MAMP/htdocs/site/vendor/yiisoft/yii2/console/controllers/HelpController.php(67): yii\console\controllers\HelpController->getDefaultHelp()
#4 [internal function]: yii\console\controllers\HelpController->actionIndex(NULL)
#5 /Applications/MAMP/htdocs/site/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#6 /Applications/MAMP/htdocs/site/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#7 /Applications/MAMP/htdocs/site/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('', Array)
#8 /Applications/MAMP/htdocs/site/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('', Array)
#9 /Applications/MAMP/htdocs/site/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('', Array)
#10 /Applications/MAMP/htdocs/site/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('', Array)
#11 /Applications/MAMP/htdocs/site/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#12 /Applications/MAMP/htdocs/site/yii(27): yii\base\Application->run()
#13 {main}

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.18
| PHP version      | 7.2.14
| Operating system | MacOS, Linux

### PR DESCRIPTION
**Pull request by alexkart**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #17395

### CODE REVIEW

**Review by samdark — APPROVED** [review]

**Comment by alexkart** [comment]
@samdark, do you have a suggestion on how to fix code climate "Controller has a coupling between objects value of 13" warning for the `\yii\base\Controller`?

**Comment by samdark** [comment]
Let's ignore it.

File: framework/base/Controller.php [hunk 1]
```diff
@@ -238,6 +238,34 @@ public function createAction($id)
...
+     * @param $id string the action ID
+     * @return string|null action method name
+     * @throws \ReflectionException
+     */
+    private function getMethodNameById($id)
+    {
+        $methodName = 'action' . str_replace(' ', '', ucwords(str_replace('-', ' ', $id)));
+        if (!method_exists($this, $methodName)) {
+            $methods = (new \ReflectionClass($this))->getMethods(\ReflectionMethod::IS_PUBLIC);
+            $methodNames = array_filter(array_map(function ($item) {
```
Comment (rob006) [inline framework/base/Controller.php]: What is happening here?

Comment (alexkart) [reply framework/base/Controller.php]: Do you suggest to split it into several lines? :)

Comment (rob006) [reply framework/base/Controller.php]: I would like to know purpose of this code first. Splitting it into separate statements is definitely helpful :) 

I don't really think we should create ambiguous route, and then try to guess method name. We should either leave `_` untouched in route or disallow it completely in action names.

Comment (alexkart) [reply framework/base/Controller.php]: I thought of this but we discussed it in the issue comments and decided to leave it this way.

File: framework/base/Controller.php [hunk 2]
```diff
@@ -238,6 +238,33 @@ public function createAction($id)
...
+        $methodName = 'action' . str_replace(' ', '', ucwords(str_replace('-', ' ', $id)));
+        if (!method_exists($this, $methodName)) {
+            $methods = (new \ReflectionClass($this))->getMethods(\ReflectionMethod::IS_PUBLIC);
+            $methodNames = array_map(static function ($item) {
+                return [
+                    'original_name' => $item->name,
+                    'name' => strtolower(str_replace('_', '', $item->name)),
+                ];
+            }, $methods);
+            $matchedMethodNames = array_filter($methodNames, static function ($item) use ($methodName) {
```
Comment (lubosdz) [inline framework/base/Controller.php]: If you created array `original_name => name` then simpler & faster code could be used e.g. `if(array_key_exists(..)){..}` rather than looping always through all method names.

**Comment by alexkart** [comment]
It's ready for review.

File: framework/helpers/BaseInflector.php [hunk 3]
```diff
@@ -410,6 +410,18 @@ public static function id2camel($id, $separator = '-')
...
     }
 
+    /**
+     * Converts a CamelCase action name into an ID in lowercase.
+     * Words in the ID are concatenated using the specified character '-'.
+     * For example, 'CreateUser' will be converted to 'create-user'.
+     * @param string $name the string to be converted
+     * @return string the resulting ID
+     */
+    public static function camel2idAction($name)
```
Comment (rob006) [inline framework/helpers/BaseInflector.php]: This is very specific method used only in one place - IMO it is better to move it to `HelpController` than clutter generic helper.

Comment (samdark) [inline framework/helpers/BaseInflector.php]: As @rob006 already noted, this method could be moved to the help command itself. It's hardly reusable.

File: tests/framework/base/ControllerTest.php [hunk 4]
```diff
@@ -44,6 +45,37 @@ public function testRunAction()
         $this->assertEquals('test1', $controller->action->id);
         $this->assertEquals('test-controller/test1', $controller->action->uniqueId);
     }
+
+    /**
+     * @dataProvider createInlineActionProvider
+     * @param $controllerClass
```
Comment (samdark) [inline tests/framework/base/ControllerTest.php]:
```suggestion
     * @param string $controllerClass
```

File: tests/framework/base/ControllerTest.php [hunk 5]
```diff
@@ -44,6 +45,37 @@ public function testRunAction()
...
+     * @param $actionId
```
Comment (samdark) [inline tests/framework/base/ControllerTest.php]:
```suggestion
     * @param string $actionId
```

File: tests/framework/base/ControllerTest.php [hunk 6]
```diff
@@ -44,6 +45,37 @@ public function testRunAction()
...
+     * @param $expectedActionMethod
```
Comment (samdark) [inline tests/framework/base/ControllerTest.php]:
```suggestion
     * @param string|null $expectedActionMethod
```

**Review by samdark — APPROVED** [review]
All good except what @rob006 mentioned.

File: framework/helpers/BaseInflector.php (hunk 3 above)
Comment (alexkart) [reply framework/helpers/BaseInflector.php]: This method also uses the private method `self::encoding()` copy it to the `HelpController` as well?

Comment (rob006) [reply framework/helpers/BaseInflector.php]: It is used only for processing method name, IMO we could just hardcode `UTF-8`.

File: framework/console/controllers/HelpController.php [hunk 7]
```diff
@@ -557,4 +556,16 @@ protected function getDefaultHelpHeader()
...
     }
+
+    /**
+     * Converts a CamelCase action name into an ID in lowercase.
+     * Words in the ID are concatenated using the specified character '-'.
+     * For example, 'CreateUser' will be converted to 'create-user'.
+     * @param string $name the string to be converted
+     * @return string the resulting ID
+     */
+    protected function camel2id($name)
```
Comment (rob006) [inline framework/console/controllers/HelpController.php]: `protected` -> `private`?

File: framework/console/controllers/HelpController.php [hunk 8]
```diff
@@ -258,7 +257,7 @@ protected function getModuleCommands($module)
                 if ($this->validateControllerClass($controllerClass)) {
                     $dir = ltrim(pathinfo($relativePath, PATHINFO_DIRNAME), '\\/');
 
-                    $command = Inflector::camel2id(substr(basename($file), 0, -14), '-', true);
+                    $command = $this->camel2id(substr(basename($file), 0, -14));
```
Comment (rob006) [inline framework/console/controllers/HelpController.php]: Any explanation why this was changed? Original issue was only about action names.

File: framework/console/controllers/HelpController.php [hunk 9]
```diff
@@ -532,7 +531,7 @@ protected function formatOptionHelp($name, $required, $type, $defaultValue, $com
     protected function formatOptionAliases($controller, $option)
     {
         foreach ($controller->optionAliases() as $name => $value) {
-            if (Inflector::camel2id($value, '-', true) === $option) {
+            if ($this->camel2id($value) === $option) {
```
Comment (rob006) [inline framework/console/controllers/HelpController.php]: Any explanation why this was changed? Original issue was only about action names.

**Review by samdark — APPROVED** [review]

**Comment by alexkart** [comment]
Is everything correct?
@rob006, I believe we are waiting for your approval.

**Review by rob006 — APPROVED** [review]

**Comment by samdark** [comment]
Merged. Thank you very much!
