### PR TITLE
trim @web before looking for the asset in webroot, fixes #18414

### LINKED ISSUE #18414: AssetManager appendTimestamp not working
### What steps will reproduce the problem?
asset-config:

	'app\assets\BootstrapAsset' => [
		'basePath' => '@webroot',
		'baseUrl' => '@web',
		'css' => ['css/site.min.css'],
	],

web.php

    'components' => [
    ...
		'assetManager' => [
			'appendTimestamp' => true,
			'bundles' => require(__DIR__ . '/asset-bundles.php'),
		],

### What is the expected result?
the site.min.css with the query parameter `v=time()`
`<link href="/my-project/web/css/site.min.css?v=123" rel="stylesheet">`

### What do you get instead?
no timestamp:

`<link href="/my-project/web/css/site.min.css" rel="stylesheet">`

### Additional info

this happens because of Line 495 in View.php (https://github.com/yiisoft/yii2/blob/master/framework/web/View.php#L495) it adds `@webroot` to the url. But the Url comes from the AssetManager (newly introduced `getActualAssetUrl` method (https://github.com/yiisoft/yii2/blob/c46d209b56fda9aca05a9cc7fc858ce2fe25477d/framework/web/AssetManager.php#L643))
which already includes the `@webroot` (or other baseUrl) in the url.

The error occours now because the AssetBundle calls this new Method which is the url without the timestamp. In earlier versions the timestamp was alredy included in the $url and no errors occoured.

Possible fixes:
- Either call the old `getAssetUrl` method in the AssetBundle
- Or do not append `@webroot` in front of the url.

Btw: is there a unit test checking the appendTimestamp behavior?

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.39
| PHP version      | 7.4
| Operating system | Windows / Linux, happens on both

### PR DESCRIPTION
**Pull request by Isitar**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #18414

### CODE REVIEW

**Comment by Schaerpe** [comment]
LGTM

**Comment by samdark** [comment]
Also it seems to fail current tests.

**Comment by Isitar** [comment]
can you point out one unit test that is failing? the pipeline seems broken and doesnt run the tests?

**Comment by samdark** [comment]
Yeah. It seems it doesn't work well for your fork. Not sure why.

**Comment by samdark** [comment]
Anyway, the bug wasn't covered with tests originally and fixing it w/o a test may likely result in it appearing again.

**Comment by samdark** [comment]
Merged master into PR branch. Now test pipeline is fine.

File: framework/web/View.php [hunk 1]
```diff
@@ -492,7 +492,7 @@ private function registerFile($type, $url, $options = [], $key = null)
 
         if (empty($depends)) {
             // register directly without AssetManager
-            if ($appendTimestamp && Url::isRelative($url) && ($timestamp = @filemtime(Yii::getAlias('@webroot/' . ltrim($url, '/'), false))) > 0) {
+            if ($appendTimestamp && Url::isRelative($url) && ($timestamp = @filemtime(Yii::getAlias('@webroot/' . ltrim(ltrim($url, Yii::getAlias('@web')), '/'), false))) > 0) {
```
Comment (rob006) [inline framework/web/View.php:495]: This is not how trim works. All trim functions remove **chars** specified in second argument, so this will not only remove leading `Yii::getAlias('@web')` but also any further chars that are included in `@web` alias. Example: https://3v4l.org/Rjvgi

Comment (Isitar) [reply framework/web/View.php:495]: Please read carefully, we use `ltrm` https://www.php.net/manual/de/function.ltrim.php

Comment (Mister-42) [reply framework/web/View.php:495]: See https://3v4l.org/ARlHc As indicated by @rob006 all trim functions work that way.

Comment (Isitar) [reply framework/web/View.php]: i replaced it with another solution. I also added a unit test to cover this scenario.

**Comment by Isitar** [comment]
Added Unit test, it should be fine now :)

File: framework/web/View.php [hunk 2]
```diff
@@ -492,8 +492,13 @@ private function registerFile($type, $url, $options = [], $key = null)
 
         if (empty($depends)) {
             // register directly without AssetManager
-            if ($appendTimestamp && Url::isRelative($url) && ($timestamp = @filemtime(Yii::getAlias('@webroot/' . ltrim($url, '/'), false))) > 0) {
-                $url = $timestamp ? "$url?v=$timestamp" : $url;
+            if ($appendTimestamp && Url::isRelative($url)) {
+                $prefix = Yii::getAlias('@web');
+                $trimmed_url = ltrim((substr($url, 0, strlen($prefix)) === $prefix) ? substr($url, strlen($prefix)) : $url, '/');
```
Comment (bizley) [inline framework/web/View.php:497]: `$trimmed_url` -> `$trimmedUrl`
Extract `strlen($prefix)` to a variable.

**Review by bizley — CHANGES_REQUESTED** [review]

File: framework/web/View.php [hunk 3]
```diff
@@ -492,8 +492,14 @@ private function registerFile($type, $url, $options = [], $key = null)
 
         if (empty($depends)) {
             // register directly without AssetManager
-            if ($appendTimestamp && Url::isRelative($url) && ($timestamp = @filemtime(Yii::getAlias('@webroot/' . ltrim($url, '/'), false))) > 0) {
-                $url = $timestamp ? "$url?v=$timestamp" : $url;
+            if ($appendTimestamp && Url::isRelative($url)) {
+                $prefix = Yii::getAlias('@web');
+                $prefixStrlen = strlen($prefix);
+                $trimmedUrl = ltrim((substr($url, 0, $prefixStrlen) === $prefix) ? substr($url, $prefixStrlen) : $url, '/');
+                $timestamp =  @filemtime(Yii::getAlias('@webroot/' . $trimmedUrl, false));
```
Comment (bizley) [inline framework/web/View.php:499]:
```suggestion
                $timestamp = @filemtime(Yii::getAlias('@webroot/' . $trimmedUrl, false));
```

**Review by bizley — CHANGES_REQUESTED** [review]
;)

**Review by bizley — APPROVED** [review]

**Review by samdark — APPROVED** [review]

**Comment by Isitar** [comment]
I don't want to nitpick, but your minor enhancement is actually worse performance-wise (at least in newer php versions):
https://stackoverflow.com/a/7168986/4903754

anyway I'm looking forward for this to be merged and released so I dont have to ctrl+f5 anymore in my dev-environment

**Comment by Isitar** [comment]
Ignore it, you already reverted it 👍

**Comment by samdark** [comment]
Done. Thanks.
