### PR TITLE
Fix #17760: Fix `JSON::encode()` for `\DateTimeInterface` under PHP 7.4

### LINKED ISSUE #17760: JSON::encode for DateTime
### What steps will reproduce the problem?
`echo \yii\helpers\Json::encode(['date' => new \DateTime()]);`

### What is the expected result?
`{"date":{"date":"2019-12-23 15:52:27.717576","timezone_type":3,"timezone":"UTC"}}`

### What do you get instead?
`{"date":{}}`

But when I run native php `json_encode`:
`echo json_encode(['date' => new \DateTime()]);`

Returns expected result:
`{"date":{"date":"2019-12-23 15:52:27.717576","timezone_type":3,"timezone":"UTC"}}`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.31
| PHP version      | 7.4.0 (cli)
| Operating system | Debian 10

### PR DESCRIPTION
**Pull request by samdark**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #17760

### CODE REVIEW

File: framework/helpers/BaseJson.php [hunk 1]
```diff
@@ -151,9 +151,17 @@ protected static function processData($data, &$expressions, $expPrefix)
...
                 return $token;
-            } elseif ($data instanceof \JsonSerializable) {
+            }
+
+            if ($data instanceof \JsonSerializable) {
                 return static::processData($data->jsonSerialize(), $expressions, $expPrefix);
-            } elseif ($data instanceof Arrayable) {
+            }
+
+            if ($data instanceof \DateTimeInterface) {
```
Comment (xepozz) [inline framework/helpers/BaseJson.php]: DateTimeInterface appeared only in 5.5 version (https://www.php.net/manual/en/class.datetimeinterface.php)
So it breaks BC, because Yii2 supports minimal 5.4 version https://github.com/yiisoft/yii2/blob/2.0.31/composer.json#L71

**Review by xepozz — CHANGES_REQUESTED** [review]

File: framework/helpers/BaseJson.php (hunk 1 above)
Comment (rob006) [reply framework/helpers/BaseJson.php]: `instanceof` works fine with non-existing types - you don't need to have `DateTimeInterface`  to know that `$data` is not `DateTimeInterface`.

**Review by rob006 — APPROVED** [review]

File: framework/helpers/BaseJson.php (hunk 1 above)
Comment (samdark) [reply framework/helpers/BaseJson.php]: Since the issue doesn't affect PHP versions lower than 7.4, non-existence of `\DateTimeInterface` is fine.
