### PR TITLE
fixes #11040: make copyDirectory method work correctly with parameter 'recursive'

### LINKED ISSUE #11040: Parameter 'recursive' not work in function FileHelper::copyDirectory
Documentation has description: 
```doc
recursive: boolean, whether the files under the subdirectories should also be copied. Defaults to true.
```
But, it not working.

### PR DESCRIPTION
**Pull request by pchapl**
Closes #11040

### CODE REVIEW

File: tests/framework/helpers/FileHelperTest.php [hunk 1]
```diff
@@ -138,6 +138,85 @@ public function testCopyDirectory()
...
+
+        $basePath = $this->testFilePath;
+        $srcDirName = $basePath . DIRECTORY_SEPARATOR . $srcDirName;
+        $dstDirName = $basePath . DIRECTORY_SEPARATOR . 'test_dst_dir';
+
+        FileHelper::copyDirectory($srcDirName, $dstDirName);
+
+        $this->assertFileExists($dstDirName, 'Destination directory does not exist!');
+
+        $checker = function ($structure, $dstDirName) use (&$checker) {
```
Comment (SilverFire) [inline tests/framework/helpers/FileHelperTest.php]: Why did you put this algorithm in the closure?

Comment (Ni-san) [inline tests/framework/helpers/FileHelperTest.php]: I think there is no need to create a separate method that used and can be used only in one place

Comment (SilverFire) [inline tests/framework/helpers/FileHelperTest.php]: Why it can't be done without putting it in a closure? It's not a problem or principle question, I'm just asking to know, what is the idea of this approach.

Comment (kidol) [inline tests/framework/helpers/FileHelperTest.php]: It's calling itself recursively.

Comment (SilverFire) [inline tests/framework/helpers/FileHelperTest.php]: Oh, sorry, I've missed it

**Comment by SilverFire** [comment]
Merged, thank you!
