### PR TITLE
fixes #7757: in oci schema fix query results row keys case

### LINKED ISSUE #7757: Yii2 OCI schema reader fails due to hardcoded uppercase column names
My ActiveRecord class works against Oracle database. The connection configuration for Oracle database has PDO setting to force all columns names to the lower case:

```php
'attributes' => [
			PDO::ATTR_CASE => PDO::CASE_LOWER,
		],
```

Table schema reader fails when reading the results:

```
2015-03-17 06:39:49 [127.0.0.1][YYY][fqnk7tbu7b6op2947ekcc9ce96][info][yii\db\Command::query] SELECT * FROM "XXX"."XXX" WHERE "ID"=123
2015-03-17 06:39:49 [127.0.0.1][YYY][fqnk7tbu7b6op2947ekcc9ce96][info][yii\db\Connection::open] Opening DB connection: oci:dbname=ZZZ
2015-03-17 06:39:51 [127.0.0.1][YYY][fqnk7tbu7b6op2947ekcc9ce96][info][yii\db\Command::query] SELECT a.column_name, a.data_type ||
    case
        when data_precision is not null
            then '(' || a.data_precision ||
                    case when a.data_scale > 0 then ',' || a.data_scale else '' end
                || ')'
        when data_type = 'DATE' then ''
        when data_type = 'NUMBER' then ''
        else '(' || to_char(a.data_length) || ')'
    end as data_type,
    a.nullable, a.data_default,
    (   SELECT D.constraint_type
        FROM ALL_CONS_COLUMNS C
        inner join ALL_constraints D on D.OWNER = C.OWNER and D.constraint_name = C.constraint_name
        WHERE C.OWNER = B.OWNER
           and C.table_name = B.object_name
           and C.column_name = A.column_name
           and D.constraint_type = 'P') as Key,
    com.comments as column_comment
FROM ALL_TAB_COLUMNS A
inner join ALL_OBJECTS B ON b.owner = a.owner and ltrim(B.OBJECT_NAME) = ltrim(A.TABLE_NAME)
LEFT JOIN all_col_comments com ON (A.owner = com.owner AND A.table_name = com.table_name AND A.column_name = com.column_name)
WHERE
    a.owner = 'XXX'
    and (b.object_type = 'TABLE' or b.object_type = 'VIEW')
    and b.object_name = 'XXX'
ORDER by a.column_id
2015-03-17 06:40:10 [127.0.0.1][YYY][fqnk7tbu7b6op2947ekcc9ce96][error][yii\base\ErrorException:8] exception 'yii\base\ErrorException' with message 'Undefined index: COLUMN_NAME' in C:\inetpub\sites\qtyii2\vendor\yiisoft\yii2\db\oci\Schema.php:208
Stack trace:
#0 C:\inetpub\sites\qtyii2\vendor\yiisoft\yii2\db\oci\Schema.php(208): yii\base\ErrorHandler->handleError(8, 'Undefined index...', 'C:\\inetpub\\site...', 208, Array)
#1 C:\inetpub\sites\qtyii2\vendor\yiisoft\yii2\db\oci\Schema.php(149): yii\db\oci\Schema->createColumn(Array)
#2 C:\inetpub\sites\qtyii2\vendor\yiisoft\yii2\db\oci\Schema.php(69): yii\db\oci\Schema->findColumns(Object(yii\db\TableSchema))
#3 C:\inetpub\sites\qtyii2\vendor\yiisoft\yii2\db\Schema.php(125): yii\db\oci\Schema->loadTableSchema('EMCCS.EMCCS_SR_...')
#4 C:\inetpub\sites\qtyii2\vendor\yiisoft\yii2\db\ActiveRecord.php(297): yii\db\Schema->getTableSchema('EMCCS.EMCCS_SR_...')
#5 C:\inetpub\sites\qtyii2\vendor\yiisoft\yii2\db\ActiveRecord.php(370): yii\db\ActiveRecord::getTableSchema()
#6 C:\inetpub\sites\qtyii2\vendor\yiisoft\yii2\db\ActiveQueryTrait.php(132): yii\db\ActiveRecord::populateRecord(Object(dryu\qtool\db\crmspx\Environment), Array)
#7 C:\inetpub\sites\qtyii2\vendor\yiisoft\yii2\db\ActiveQuery.php(218): yii\db\ActiveQuery->createModels(Array)
#8 C:\inetpub\sites\qtyii2\vendor\yiisoft\yii2\db\ActiveQuery.php(287): yii\db\ActiveQuery->populate(Array)
#9 C:\inetpub\sites\qtyii2\frontend\views\view\sr\details\env.php(16): yii\db\ActiveQuery->one()
#10 C:\inetpub\sites\qtyii2\vendor\yiisoft\yii2\base\View.php(325): require('C:\\inetpub\\site...')
#11 C:\inetpub\sites\qtyii2\vendor\yiisoft\yii2\base\View.php(247): yii\base\View->renderPhpFile('C:\\inetpub\\site...', Array)
#12 C:\inetpub\sites\qtyii2\vendor\yiisoft\yii2\base\View.php(149): yii\base\View->renderFile('C:\\inetpub\\site...', Array, Object(frontend\controllers\ViewController))
#13 C:\inetpub\sites\qtyii2\vendor\yiisoft\yii2\base\Controller.php(398): yii\base\View->render('sr/details/env', Array, Object(frontend\controllers\ViewController))
#14 C:\inetpub\sites\qtyii2\frontend\controllers\ViewController.php(161): yii\base\Controller->renderPartial('sr/details/env', Array)
#15 [internal function]: frontend\controllers\ViewController->actionSr('NNN')
#16 C:\inetpub\sites\qtyii2\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array)
#17 C:\inetpub\sites\qtyii2\vendor\yiisoft\yii2\base\Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#18 C:\inetpub\sites\qtyii2\vendor\yiisoft\yii2\base\Module.php(455): yii\base\Controller->runAction('sr', Array)
#19 C:\inetpub\sites\qtyii2\vendor\yiisoft\yii2\web\Application.php(83): yii\base\Module->runAction('view/sr', Array)
#20 C:\inetpub\sites\qtyii2\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#21 C:\inetpub\sites\qtyii2\frontend\web\index.php(17): yii\base\Application->run()
#22 {main}
```

because it has all default names hardcoded in the uppercase:

```php
/**
     * Creates ColumnSchema instance
     *
     * @param array $column
     * @return ColumnSchema
     */
    protected function createColumn($column)
    {
        $c = $this->createColumnSchema();
        $c->name = $column['COLUMN_NAME'];
        $c->allowNull = $column['NULLABLE'] === 'Y';
        $c->isPrimaryKey = strpos($column['KEY'], 'P') !== false;
        $c->comment = $column['COLUMN_COMMENT'] === null ? '' : $column['COLUMN_COMMENT'];
 
        $this->extractColumnType($c, $column['DATA_TYPE']);
        $this->extractColumnSize($c, $column['DATA_TYPE']);
 
        $c->phpType = $this->getColumnPhpType($c);
```

Yii 2.0.2.

### PR DESCRIPTION
**Pull request by nineinchnick**
fixes #7757: in oci schema fix query results row keys case when PDO::ATTR_CASE is set to PDO::CASE_LOWER

### CODE REVIEW

**Comment by samdark** [comment]
What if case is neutral?

**Comment by nineinchnick** [comment]
Then the results contains keys as specified in the query, so uppercase.

I admin I have not run this. I'll try to install Oracle at home because I'm getting more interested in it.

**Comment by samdark** [comment]
Great.

**Comment by nineinchnick** [comment]
I forgot to add - `PDO::CASE_NATURAL` is the default value for `PDO::ATTR_CASE`.

**Comment by nineinchnick** [comment]
Ohh and it's a good idea to add a unit test for this. It could also check other databases.

**Comment by samdark** [comment]
Agree.

**Comment by nineinchnick** [comment]
Added `oci` tests, but the whole `oci` schema implementation is a total mess. Column types are not detected properly. I'm going to fix that before adding case tests.

**Comment by nineinchnick** [comment]
I feel like the tests I wrote here are some schema fixes should be moved to another PR. Can anybody take a look?

File: framework/db/oci/Schema.php [hunk 1]
```diff
@@ -276,6 +293,9 @@ protected function findTableNames($schema = '')
         $rows = $command->queryAll();
         $names = [];
         foreach ($rows as $row) {
+            if ($this->db->slavePdo->getAttribute(\PDO::ATTR_CASE) == \PDO::CASE_LOWER) {
```
Comment (samdark) [inline framework/db/oci/Schema.php]: `===`?

File: framework/db/oci/Schema.php [hunk 2]
```diff
@@ -146,12 +137,16 @@ protected function findColumns($table)
         }
 
         foreach ($columns as $column) {
+            if ($this->db->slavePdo->getAttribute(\PDO::ATTR_CASE) == \PDO::CASE_LOWER) {
```
Comment (samdark) [inline framework/db/oci/Schema.php]: `===`?

File: framework/db/oci/Schema.php [hunk 3]
```diff
@@ -219,7 +215,15 @@ protected function createColumn($column)
             if (stripos($column['DATA_DEFAULT'], 'timestamp') !== false) {
                 $c->defaultValue = null;
             } else {
-                $c->defaultValue = $c->phpTypecast($column['DATA_DEFAULT']);
+                $defaultValue = $column['DATA_DEFAULT'];
+                if ($defaultValue !== null) {
+                    if (($len=strlen($defaultValue)) > 2 && $defaultValue[0] === "'" && $defaultValue[$len-1] === "'") {
+                        $defaultValue = substr($column['DATA_DEFAULT'], 1, -1);
```
Comment (samdark) [inline framework/db/oci/Schema.php]: Could it be multibyte?

File: framework/db/oci/Schema.php [hunk 4]
```diff
@@ -246,12 +250,25 @@ protected function findConstraints($table)
         order by d.constraint_name, c.position
 EOD;
         $command = $this->db->createCommand($sql);
+        $constraints = [];
         foreach ($command->queryAll() as $row) {
+            if ($this->db->slavePdo->getAttribute(\PDO::ATTR_CASE) == \PDO::CASE_LOWER) {
```
Comment (samdark) [inline framework/db/oci/Schema.php]: `===`?

File: framework/db/oci/Schema.php [hunk 5]
```diff
@@ -219,7 +215,15 @@ protected function createColumn($column)
             if (stripos($column['DATA_DEFAULT'], 'timestamp') !== false) {
                 $c->defaultValue = null;
             } else {
-                $c->defaultValue = $c->phpTypecast($column['DATA_DEFAULT']);
+                $defaultValue = $column['DATA_DEFAULT'];
+                if ($defaultValue !== null) {
+                    if (($len=strlen($defaultValue)) > 2 && $defaultValue[0] === "'" && $defaultValue[$len-1] === "'") {
```
Comment (samdark) [inline framework/db/oci/Schema.php]: Could it be multibyte?

File: tests/unit/framework/db/DatabaseTestCase.php [hunk 6]
```diff
@@ -19,6 +19,9 @@ protected function setUp()
         $databases = self::getParam('databases');
         $this->database = $databases[$this->driverName];
         $pdo_database = 'pdo_'.$this->driverName;
+        if ($this->driverName == 'oci') {
```
Comment (samdark) [inline tests/unit/framework/db/DatabaseTestCase.php]: `===`?

File: tests/unit/framework/db/DatabaseTestCase.php [hunk 7]
```diff
@@ -71,7 +74,13 @@ public function prepareDatabase($config, $fixture, $open = true)
         }
         $db->open();
         if ($fixture !== null) {
-            $lines = explode(';', file_get_contents($fixture));
+            if ($this->driverName == 'oci') {
```
Comment (samdark) [inline tests/unit/framework/db/DatabaseTestCase.php]: `===`?

**Comment by samdark** [comment]
Another PR could be useful but this one isn't too big to be reviewed.

File: framework/db/oci/Schema.php (hunk 3 above)
Comment (nineinchnick) [inline framework/db/oci/Schema.php]: We only check if the value is surrounded with single quotes, which can't be multibyte. I don't think it matters if the rest of the value is.

Comment (nineinchnick) [inline framework/db/oci/Schema.php]: I was also thinking about trying to detect numerics here and if the default value is neither a string nor numeric it could be wrapper as `db\Expression`.

When processing datatypes this `Schema` removes default values for timestamps. I don't know why, should this be fixed?

**Comment by nineinchnick** [comment]
I think I'm going to quote all column names in `oci.sql` to allow reusing more tests.

File: framework/db/oci/Schema.php (hunk 3 above)
Comment (samdark) [inline framework/db/oci/Schema.php]: There's `$defaultValue[$len-1]` which could go wrong for multibyte strings because of `strlen($defaultValue)`.

Comment (nineinchnick) [inline framework/db/oci/Schema.php]: Doesn't `strlen` just count bytes instead of chars? If it does, the last byte would always be a quote.

Comment (nineinchnick) [inline framework/db/oci/Schema.php]: I just didn't want to assume the value is in utf.

Comment (nineinchnick) [inline framework/db/oci/Schema.php]: The task to perform here is: check if value is surrounded by single quotes regardless of the value's encoding.

Comment (samdark) [inline framework/db/oci/Schema.php]: Automatic wrapping with `db\Expression` should be done carefully since it could easily result in security issues.

Comment (nineinchnick) [inline framework/db/oci/Schema.php]: Why? It's the default value expression from the db schema, not user input. Examples:

* numerics: `12.34`
* strings: `'something'`
* expressions: `to_timestamp('value','format')` and `CURRENT_TIMESTAMP`.

Comment (samdark) [inline framework/db/oci/Schema.php]: Right.

**Comment by nineinchnick** [comment]
I've added more tests and implemented some features like `batchInsert` along the way.

`OracleActiveRecordTest` still doesn't pass, this is the last one.

If anybody wants to run this, here's [my pdo_oci8 driver](https://github.com/nineinchnick/pdo_oci8).

**Comment by nineinchnick** [comment]
I'm done here

**Comment by nineinchnick** [comment]
Thinking about it, AR tests should include loading metadata when `PDO:ATTR_CASE` is set to `PDO::CASE_UPPER`.

**Comment by samdark** [comment]
There's at least one test failing now: https://travis-ci.org/yiisoft/yii2/jobs/56241236#L245

**Comment by nineinchnick** [comment]
@samdark I fixed one test condition. I think there was parenthesis missing, can you take a look? Now Travis fails with Cubrid setup, is it normal?

**Comment by samdark** [comment]
Cubrid fail is about travis setup. It is, of course, very annoying because of fail to see real errors.

File: framework/db/oci/QueryBuilder.php [hunk 8]
```diff
@@ -160,4 +160,61 @@ public function addForeignKey($name, $table, $columns, $refTable, $refColumns, $
...
+        $schema = $this->db->getSchema();
+        if (($tableSchema = $schema->getTableSchema($table)) !== null) {
+            $columnSchemas = $tableSchema->columns;
+        } else {
+            $columnSchemas = [];
+        }
+
+        $values = [];
+        foreach ($rows as $row) {
+            $vs = [];
```
Comment (samdark) [inline framework/db/oci/QueryBuilder.php]: Consider renaming it to something more meaningful.

File: framework/db/oci/Schema.php [hunk 9]
```diff
@@ -146,12 +145,16 @@ protected function findColumns($table)
...
+                $column = array_change_key_case($column, CASE_UPPER);
+            }
             $c = $this->createColumn($column);
             $table->columns[$c->name] = $c;
             if ($c->isPrimaryKey) {
                 $table->primaryKey[] = $c->name;
                 $table->sequenceName = $this->getTableSequenceName($table->name);
-                $c->autoIncrement = true;
+                // autoIncrement cannot be reliably detected, ex. with composite PKs
+                //$c->autoIncrement = $table->sequenceName !== null;
```
Comment (samdark) [inline framework/db/oci/Schema.php]: Should it stay there commented?

File: framework/db/oci/Schema.php [hunk 10]
```diff
@@ -219,7 +224,21 @@ protected function createColumn($column)
...
-                $c->defaultValue = $c->phpTypecast($column['DATA_DEFAULT']);
+                $defaultValue = $column['DATA_DEFAULT'];
+                if ($c->type === 'timestamp' && $defaultValue === 'CURRENT_TIMESTAMP') {
+                    $c->defaultValue = new Expression('CURRENT_TIMESTAMP');
+                } else {
+                    if ($defaultValue !== null) {
+                        if (($len = strlen($defaultValue)) > 2 && $defaultValue[0] === "'"
+                            && $defaultValue[$len - 1] === "'"
+                        ) {
+                            $defaultValue = substr($column['DATA_DEFAULT'], 1, -1);
```
Comment (samdark) [inline framework/db/oci/Schema.php]: Could it be unicode?

Comment (nineinchnick) [inline framework/db/oci/Schema.php]: We've already discussed this. Also, other schemas just trim quotes here which is invalid and could remove too much. Should I report it in another issue?

File: framework/db/oci/QueryBuilder.php (hunk 8 above)
Comment (nineinchnick) [inline framework/db/oci/QueryBuilder.php]: This is copied from the parent class, not my own code. If this to be refactored, it should be changed in other schemas, like sqlite.

**Comment by nineinchnick** [comment]
Ok I've added a test that actually tests what this issue was about and detected and fixed invalid behavior for mysql.

I can't test mssql or cubrid.

**Comment by cebe** [comment]
> Cubrid fail is about travis setup. It is, of course, very annoying because of fail to see real errors.

This is an issue with travis, not sure what is happening as there is no error output, working for me locally. I have tried to make it more robust and not kill the whole test suite on failures:
https://github.com/yiisoft/yii2/commit/fd99fe1efabb22c0c7e019ace03152f0958a5411

If you rebase on master you should be able to see real test results.

File: framework/db/oci/QueryBuilder.php (hunk 8 above)
Comment (samdark) [inline framework/db/oci/QueryBuilder.php]: OK. Let's leave it as is for now.

File: framework/db/oci/Schema.php (hunk 10 above)
Comment (samdark) [inline framework/db/oci/Schema.php]: Probably yes.

**Comment by nineinchnick** [comment]
@cebe I did and tests still fail. Anyhow, I'm done here with work except fixes if requested, moving on to gii issues.

**Comment by cebe** [comment]
Yeah but now you see it is only cubrid failing, before it was the whole test suite. Your tests seem fine. The cubrid failure is unrelated and cause by an error in the setup which I have not figured out yet.

**Comment by samdark** [comment]
@nineinchnick please add changelog and I'll merge PR.

**Comment by nineinchnick** [comment]
@samdark done.

**Comment by samdark** [comment]
Thanks!

**Comment by cebe** [comment]
@nineinchnick great job!
