### PR TITLE
Fix bug with optional params at the beginning of pattern in `yii\web\UrlRule`

### LINKED ISSUE #13086: Error with rules which include a defaults
### What steps will reproduce the problem?
I only have 1 rule which includes a defaults but it is not working as expected. 
Here is the rule

`                [
                    'pattern' => '<language>/<brand>',
                    'route' => 'site/brand',
                    'defaults' => ['language' => 'en'],
                ] 
`

If I access domain.com/brand1 I get an error "Not Found (#404)"

Note that if I setup this rule instead: 

`                [
                    'pattern' => 'test/<language>/<brand>',
                    'route' => 'site/brand',
                    'defaults' => ['language' => 'en'],
                ] 
`

and I access domain.com/test/brand1 then I get the expected result and I am redirected to site/brand with the language parameter defaulted to 'en'

### What is the expected result?

The rule should be applied and the default language set to 'en' . 

### What do you get instead?

yii\web\HttpException:404

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.10
| PHP version      | 7.0.12
| Operating system | Windows 10

### LINKED ISSUE #13656: Duplicate slashes if set param 'suffix' of the component UrlManager to '/'
### What steps will reproduce the problem?
#13522
```php
[
    'suffix'     => '/',
    ['pattern' => '<page:\d+>', 'route' => 'site/index', 'defaults' => ['page' => 1]],
]
```

Then create a URL like that

Url::to(['site/index', 'page' => 1])

### What is the expected result?
The generated URL should be
```text
<a href="/">Home</a>
```
### What do you get instead?
```text
<a href="//">Home</a>
```
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.11.2
| PHP version      | 7.0.15
| Operating system | Centos 6

Issue is not reproducible on Yii 2.0.10

### PR DESCRIPTION
**Pull request by rob006**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #13086

fixes #13086
fixes #13656
closes #13614

### CODE REVIEW

File: framework/web/UrlRule.php [hunk 1]
```diff
@@ -96,6 +96,14 @@ class UrlRule extends Object implements UrlRuleInterface
...
      */
     public $normalizer;
+    /**
+     * @var bool Value used when pattern contains only optional params. If `true` rule pattern will contain slash at
+     * the end of param pattern (last optional param can not be omitted if all other patterns are not omitted), if `false`
+     * rule pattern will contain slash at the beginning of param pattern (first optional param can not be omitted
+     * if all other patterns are not omitted).
+     * @since 2.0.12
+     */
+    public $trailingSlashForDefaults = false;
```
Comment (samdark) [inline framework/web/UrlRule.php]: Both description and name are quite vague. If you're not into the issue, it's quite hard to get the meaning...

Comment (samdark) [inline framework/web/UrlRule.php]: Should it be configurable at all?

**Review by samdark — CHANGES_REQUESTED** [review]

File: framework/web/UrlRule.php (hunk 1 above)
Comment (rob006) [inline framework/web/UrlRule.php]: I have no idea how to describe/name it better. I'm open to suggestions.

> Should it be configurable at all?

I decided to make it configurable because it is more flexible, but not sure if it is worth of API complication.

Comment (Kolyunya) [inline framework/web/UrlRule.php]: I was aware of the issue but when I fist saw this property I was totally confused.

Comment (samdark) [inline framework/web/UrlRule.php]: @rob006 why would you want buggy version of this behavior?

Comment (rob006) [inline framework/web/UrlRule.php]: @samdark Why buggy? If I have pattern like `<language>/<category>/<slug>` when all part are optional, I may have want omit params from beginning, not from the end. With `$trailingSlashForDefaults = true` valid URLs will be:
* `en/my-default-category/project-slug`
* `my-default-category/project-slug`
* `project-slug`

With `$trailingSlashForDefaults = false` valid URLs will be:
* `en/my-default-category/project-slug`
* `en/my-default-category`
* `en`

Both cases seems valid to me.

Comment (samdark) [inline framework/web/UrlRule.php]: Ah. Yes. I wonder how to name it... hard case.

Comment (Kolyunya) [inline framework/web/UrlRule.php]: What about `my-default-category` URL in both scenarios?

Comment (rob006) [inline framework/web/UrlRule.php]: > What about the following URLs in both scenarios?

First will never work, second will work on both cases.

Comment (dynasource) [inline framework/web/UrlRule.php]: > If you're not into the issue, it's quite hard to get the meaning...

when the issue is described in 1 sentence, you're already closer to a proper name

Comment (SilverFire) [inline framework/web/UrlRule.php]: Maybe, it worth to add some examples to explain what does this parameter do?

**Comment by SilverFire** [comment]
Related https://github.com/yiisoft/yii2/issues/13656

File: framework/web/UrlRule.php (hunk 1 above)
Comment (SilverFire) [inline framework/web/UrlRule.php]: How about

```php
const OMIT_FIRST = 0;
const OMIT_LAST = 1;

public $optionalParamParsingMode;
```

Comment (samdark) [inline framework/web/UrlRule.php]: Yes. That is better.

Comment (samdark) [inline framework/web/UrlRule.php]: @rob006 what do you think?

Comment (rob006) [inline framework/web/UrlRule.php]: I'm going to remove this property. It brings unnecessary complications in the API, and the same effect can be achieved with only one additional rule.

**Comment by rob006** [comment]
I removed this property. Let's focus on fixing this bugs, additional configuration options could be added in future.
🚢

**Comment by rob006** [comment]
Bump.

**Comment by lynicidn** [comment]
1. помоему это ломает обратную совместимость
2. defaultParams в тестах не нужны, так как во все тесты передаются аргументы и не один тест не проверят именно default (когда не переданы какие либо или все параметры)
3. не хватает тестов для parseRequest с default

**Comment by samdark** [comment]
@lynicidn @rob006 can't read your commen...

**Comment by samdark** [comment]
@rob006 the comment from @lynicidn was the following:

1. I think it breaks backwards compatibility.
2. `defaultParams` aren't needed in tests since all the tests are supplied with arguments and no test is checking for default (when one or more params are missing).
3. It's missing tests for `parseRequest` with `default`.

**Comment by rob006** [comment]
> I think it breaks backwards compatibility.

Any examples?

> defaultParams aren't needed in tests since all the tests are supplied with arguments and no test is checking for default (when one or more params are missing).

https://github.com/yiisoft/yii2/pull/13624/files#diff-96fb0ef29c09f20871090c41bf5b3839R999 ?

> It's missing tests for parseRequest with default.

https://github.com/yiisoft/yii2/pull/13624/files#diff-96fb0ef29c09f20871090c41bf5b3839R971 ?

File: framework/web/UrlRule.php [hunk 2]
```diff
@@ -179,6 +179,11 @@ public function init()
             $this->name = $this->pattern;
         }
 
+        $this->preparePattern();
+    }
+
+    private function preparePattern()
```
Comment (samdark) [inline framework/web/UrlRule.php]: phpdoc missing

File: framework/web/UrlRule.php [hunk 3]
```diff
@@ -212,6 +217,11 @@ public function init()
             }
         }
 
+        $this->translatePattern(true);
+    }
+
+    private function translatePattern($allowAppendSlash)
```
Comment (samdark) [inline framework/web/UrlRule.php]: phpdoc missing

File: framework/web/UrlRule.php [hunk 4]
```diff
@@ -232,14 +245,34 @@ public function init()
...
                     $offset = $match[0][1];
-                    if ($offset > 1 && $this->pattern[$offset - 1] === '/' && (!isset($this->pattern[$offset + $length]) || $this->pattern[$offset + $length] === '/')) {
+                    $requiredPatternPart = str_replace("/{$match[0][0]}/", '//', $requiredPatternPart);
+                    if (
+                        $allowAppendSlash
+                        && ($appendSlash || $offset === 1)
+                        && (($offset - $oldOffset) === 1)
+                        && isset($this->pattern[$offset + $length])
+                        && $this->pattern[$offset + $length] === '/'
+                        && isset($this->pattern[$offset + $length + 1])
```
Comment (samdark) [inline framework/web/UrlRule.php]: This one could be merged into previous isset:

```php
isset($this->pattern[$offset + $length], $this->pattern[$offset + $length + 1])
```

**Review by samdark — CHANGES_REQUESTED** [review]

File: framework/web/UrlRule.php (hunk 2 above)
Comment (rob006) [inline framework/web/UrlRule.php]: This is private method - to we need phpdoc for these?

Comment (samdark) [inline framework/web/UrlRule.php]: Yes.

File: framework/web/UrlRule.php (hunk 4 above)
Comment (rob006) [inline framework/web/UrlRule.php]: I think it will be less readable - it is easy to miss additional params in `isset`.

Comment (samdark) [inline framework/web/UrlRule.php]: Makes sense.

File: framework/web/UrlRule.php (hunk 2 above)
Comment (rob006) [inline framework/web/UrlRule.php]: Done.

**Review by samdark — APPROVED** [review]

**Review by SilverFire — APPROVED** [review]

**Comment by samdark** [comment]
Merged. Thank you very much!
