### PR TITLE
Closes #17504. Fix upsert 

### LINKED ISSUE #17504: yii\db\mysql\QueryBuilder::upsert produce invalid SQL on upsert if all columns in table are unique
Lets take a SQL table with 2 columns, which is composite primary key:

```sql
CREATE TABLE `blog_categ` (
  `categ_id` int(10) unsigned NOT NULL,
  `blog_id` int(10) unsigned NOT NULL,
  PRIMARY KEY (`categ_id`,`blog_id`),
)
```
Executing model upsert:
```php
static::getDb()->createCommand()->upsert(static::tableName(), $values, true)->execute();
```
Produce incorrect SQL error with empty UPDATE list:
```sql
INSERT INTO `blog_categ` (`categ_id`, `blog_id`) VALUES (2244, 139) ON DUPLICATE KEY UPDATE
```
The correct SQL will be:
```sql
INSERT INTO `blog_categ` (`categ_id`, `blog_id`) VALUES (2244, 139) ON DUPLICATE KEY UPDATE `categ_id`=`categ_id`
```
If all columns are unique, then QueryBuilder::prepareUpsertColumns return empty list of $updateNames and produce incorrect sql.  So, when $updateNames is empty, the behavior must be the same as when $updateColumns = false.

Small fix to yii\db\mysql\QueryBuilder::upsert($table, $insertColumns, $updateColumns, &$params)
```php
        --- } elseif ($updateColumns === false) {
        +++ } elseif ($updateColumns === false || empty($updateNames)) { 
```
Please, add this fix.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.24
| PHP version      | 
| Operating system |

### PR DESCRIPTION
**Pull request by alexkart**
Fix upsert when `$updateColumns = true` but there is no columns to update in the tale.

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | #17504

### CODE REVIEW

File: framework/db/cubrid/QueryBuilder.php [hunk 1]
```diff
@@ -70,6 +70,10 @@ public function upsert($table, $insertColumns, $updateColumns, &$params)
         if (empty($uniqueNames)) {
             return $this->insert($table, $insertColumns, $params);
         }
+        if ($updateNames === []) {
+            // there is no columns to update
```
Comment (samdark) [inline framework/db/cubrid/QueryBuilder.php]:
```suggestion
            // there are no columns to update
```

File: framework/db/mssql/QueryBuilder.php [hunk 2]
```diff
@@ -454,6 +454,10 @@ public function upsert($table, $insertColumns, $updateColumns, &$params)
         if (empty($uniqueNames)) {
             return $this->insert($table, $insertColumns, $params);
         }
+        if ($updateNames === []) {
+            // there is no columns to update
```
Comment (samdark) [inline framework/db/mssql/QueryBuilder.php]:
```suggestion
            // there are no columns to update
```

File: framework/db/mysql/QueryBuilder.php [hunk 3]
```diff
@@ -278,6 +278,10 @@ public function upsert($table, $insertColumns, $updateColumns, &$params)
         if (empty($uniqueNames)) {
             return $insertSql;
         }
+        if ($updateNames === []) {
+            // there is no columns to update
```
Comment (samdark) [inline framework/db/mysql/QueryBuilder.php]:
```suggestion
            // there are no columns to update
```

File: framework/db/oci/QueryBuilder.php [hunk 4]
```diff
@@ -218,6 +218,10 @@ public function upsert($table, $insertColumns, $updateColumns, &$params)
         if (empty($uniqueNames)) {
             return $this->insert($table, $insertColumns, $params);
         }
+        if ($updateNames === []) {
+            // there is no columns to update
```
Comment (samdark) [inline framework/db/oci/QueryBuilder.php]:
```suggestion
            // there are no columns to update
```

File: framework/db/pgsql/QueryBuilder.php [hunk 5]
```diff
@@ -338,6 +338,10 @@ private function newUpsert($table, $insertColumns, $updateColumns, &$params)
         if (empty($uniqueNames)) {
             return $insertSql;
         }
+        if ($updateNames === []) {
+            // there is no columns to update
```
Comment (samdark) [inline framework/db/pgsql/QueryBuilder.php]:
```suggestion
            // there are no columns to update
```

File: framework/db/pgsql/QueryBuilder.php [hunk 6]
```diff
@@ -368,6 +372,10 @@ private function oldUpsert($table, $insertColumns, $updateColumns, &$params)
         if (empty($uniqueNames)) {
             return $this->insert($table, $insertColumns, $params);
         }
+        if ($updateNames === []) {
+            // there is no columns to update
```
Comment (samdark) [inline framework/db/pgsql/QueryBuilder.php]:
```suggestion
            // there are no columns to update
```

File: framework/db/sqlite/QueryBuilder.php [hunk 7]
```diff
@@ -74,6 +74,10 @@ public function upsert($table, $insertColumns, $updateColumns, &$params)
         if (empty($uniqueNames)) {
             return $this->insert($table, $insertColumns, $params);
         }
+        if ($updateNames === []) {
+            // there is no columns to update
```
Comment (samdark) [inline framework/db/sqlite/QueryBuilder.php]:
```suggestion
            // there are no columns to update
```

File: tests/framework/db/oci/QueryBuilderTest.php [hunk 8]
```diff
@@ -239,6 +239,10 @@ public function upsertProvider()
         foreach ($concreteData as $testName => $data) {
             $newData[$testName] = array_replace($newData[$testName], $data);
         }
+
+        // skip test
+        unset($newData['no columns to update']);
```
Comment (samdark) [inline tests/framework/db/oci/QueryBuilderTest.php]: Why skipping it? It was changed in OCI builder.

File: tests/framework/db/cubrid/QueryBuilderTest.php [hunk 9]
```diff
@@ -107,6 +107,10 @@ public function upsertProvider()
         foreach ($concreteData as $testName => $data) {
             $newData[$testName] = array_replace($newData[$testName], $data);
         }
+
+        // skip test
+        unset($newData['no columns to update']);
```
Comment (samdark) [inline tests/framework/db/cubrid/QueryBuilderTest.php]: Why skipping it? It was changed in the CUBRID builder.

File: tests/framework/db/oci/QueryBuilderTest.php (hunk 8 above)
Comment (alexkart) [reply tests/framework/db/oci/QueryBuilderTest.php]: Yes, but I don't have oci to run tests with it.

File: tests/framework/db/cubrid/QueryBuilderTest.php (hunk 9 above)
Comment (alexkart) [reply tests/framework/db/cubrid/QueryBuilderTest.php]: Yes, but I don't have cubrid to run tests with it.

File: tests/framework/db/oci/QueryBuilderTest.php (hunk 8 above)
Comment (samdark) [reply tests/framework/db/oci/QueryBuilderTest.php]: Travis has it.

File: tests/framework/db/cubrid/QueryBuilderTest.php (hunk 9 above)
Comment (samdark) [reply tests/framework/db/cubrid/QueryBuilderTest.php]: OK but it should be removed before merge.

File: tests/framework/db/oci/QueryBuilderTest.php (hunk 8 above)
Comment (alexkart) [reply tests/framework/db/oci/QueryBuilderTest.php]: I think it doesn't https://github.com/yiisoft/yii2/blob/master/.travis.yml#L31

File: tests/framework/db/cubrid/QueryBuilderTest.php (hunk 9 above)
Comment (alexkart) [reply tests/framework/db/cubrid/QueryBuilderTest.php]: In this case, we need to add the expected sql query, but I don't know what the correct query is and whether it matches the actual query without running the test.

File: tests/framework/db/oci/QueryBuilderTest.php (hunk 8 above)
Comment (samdark) [reply tests/framework/db/oci/QueryBuilderTest.php]: Oh, bad... Anyway, that's not the reason to exclude it.

File: tests/framework/db/cubrid/QueryBuilderTest.php (hunk 9 above)
Comment (samdark) [reply tests/framework/db/cubrid/QueryBuilderTest.php]: As for CUBRID, that is acceptable :)

**Comment by samdark** [comment]
Thank you!
