### PR TITLE
Fixed bug with integer attributes

### LINKED ISSUE #17233: Validator attribute problem since version 2.0.17
image

### What steps will reproduce the problem?

We are creating a dynamic model and use the ActiveForm widget afterwards to render the model, this seems to throw the above error since version 2.0.17, with version 2.0.16 it works.

```php
$model = new DynamicModel();
foreach ($organisation->properties as $prop) {
            $model->defineAttribute($prop->id);
            $model->addRule([$prop->id], SafeValidator::class);
            $model->{$prop->id} = ApiOrganisationPropertyValue::getValue($prop, $this->attachedContext);
}
```

Now using ActiveForm for the generate dynamic model throws the warning above (screenshot).

```php
<?= $form->field($model, $vp->id);
```

(i made a check on the `$model` to see if the attribute exists - yes it does. via `$model->hasAttribute($vp->id)`)

### What is the expected result?

No warrnings.

### What do you get instead?

The warnning screenshot

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.17
| PHP version      | 
| Operating system |

### PR DESCRIPTION
**Pull request by nadar**
If an attribute is an integer value, is_string won't work, and a warning will be raised.

This will fix #17233

Maybe we should use 

```php
if (!is_array($attributes)) {

}
```

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes/no
| Fixed issues  | #17233

### CODE REVIEW

File: framework/validators/Validator.php [hunk 1]
```diff
@@ -277,7 +277,7 @@ public function getValidationAttributes($attributes = null)
             return $this->getAttributeNames();
         }
 
-        if (is_string($attributes)) {
+        if (is_scalar($attributes)) {
```
Comment (samdark) [inline framework/validators/Validator.php]: Why do you have int there? It's a list of attribute names according to phpdoc of both parent method and this method.

Comment (rob006) [reply framework/validators/Validator.php]: @samdark Technically object in PHP can have property like `123`.

Comment (nadar) [reply framework/validators/Validator.php]: We have generated the model and the form dynamically, so to have an unique identifier we have used the tables id - its not very common indeed, but it can happen though. Therefore just checking `if (!is_array($attributes))` would be safe as well.

Comment (samdark) [reply framework/validators/Validator.php]: `!is_array` is true for objects and resources so it looks like a bad idea.

Comment (samdark) [reply framework/validators/Validator.php]: Are `float` properties possible?

Comment (samdark) [reply framework/validators/Validator.php]: I've put together a test case: https://3v4l.org/dQ5Yv

All the properties are strings...

Comment (samdark) [reply framework/validators/Validator.php]: So yes, your fix could be applied, I think.

**Comment by samdark** [comment]
@nadar would you please put together a unit test for it and add a line for changelog?

**Comment by nadar** [comment]
@samdark yes of course

File: framework/validators/Validator.php (hunk 1 above)
Comment (rob006) [reply framework/validators/Validator.php]: > All the properties are strings...

`var_dump()` will report `string`, but integer properties will be cast to `int` if you try to export them as array: https://3v4l.org/4YZcV

**Comment by samdark** [comment]
@nadar still interested in this one?

**Comment by nadar** [comment]
Yes

**Comment by nadar** [comment]
@samdark I just detected that Validator::getAttributeNames() will convert int values into strings, therefore strict compare of in_array won't work anymore. So, either remove strict compare or take the solution i submitted which wont apply ltrim on int values. What do you think?

**Comment by samdark** [comment]
Non-strict comparison, in my opinion, looks better.

**Comment by samdark** [comment]
Travis tests failed btw.

**Comment by nadar** [comment]
Ok, i removed strict compare. Let me know if you should remove the comment, but it explains why this has ben explizit turned off.

(Yes it failed - PHP 5.4 ftw!)

**Comment by nadar** [comment]
Do you need a changelog entry? Would need to merge upstream first.

**Comment by samdark** [comment]
Yes. Need a changelog entry. Updated branch from master.

**Comment by samdark** [comment]
Merged. Thank you!
