### PR TITLE
Fixes #15627: Corrected session freezing/unfreezing not to attempt opening or closing connection if it isn't necessary

### LINKED ISSUE #15627: Session methods used before they are initialized
### What steps will reproduce the problem?
After this bugix:
[Bug #15523](https://github.com/yiisoft/yii2/commit/24f4e3126a9f6562a78ea55ad058f9c155ef09af)

When I use:

```
$config = [
    'components' => [
        'cache' => [
            'class' => yii\mongodb\Cache::className(),
        ],
        'session' => [
            'class' => yii\web\CacheSession::className(),
            'useCookies' => true,
            'timeout' => 60 * 60 * 24 * 14,
        ],
    ]
];
```

But I've noticed that any other session has this problem too

### What is the expected result?
Sessions are initialized and just work.

### What do you get instead?
It seems that the new methods `freeze()` and `unfreeze()` are triggering `readSession()` before `init()` is called resulting in reading `$this->cache->get($this->calculateKey($id));` when `$this->cache` is just a string at that moment since it was not initialized in `init()` as `$this->cache = Instance::ensure($this->cache, 'yii\caching\CacheInterface');`

```
exception 'yii\base\ErrorException' with message 'Call to a member function getCollection() on a non-object' in /var/www/project/vendor/yiisoft/yii2-mongodb/Session.php:114
Stack trace:
#0 /var/www/project/vendor/yiisoft/yii2/web/Session.php(137): ::session_start()
#1 /var/www/project/vendor/yiisoft/yii2/web/Session.php(938): yii\web\Session->open()
#2 /var/www/project/vendor/yiisoft/yii2/web/Session.php(432): yii\web\Session->unfreeze()
#3 /var/www/project/vendor/yiisoft/yii2/base/Component.php(180): yii\web\Session->setUseCookies('')
#4 /var/www/project/vendor/yiisoft/yii2/base/BaseObject.php(532): yii\base\Component->__set('', '')
#5 /var/www/project/vendor/yiisoft/yii2/base/BaseObject.php(106): yii\BaseYii::configure('', '')
#6 /var/www/project/vendor/yiisoft/yii2/di/Container.php(383): yii\base\BaseObject->__construct('')
#7 /var/www/project/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs('')
#8 /var/www/project/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('', '', '')
#9 /var/www/project/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('', '', '')
#10 /var/www/project/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject('', '')
#11 /var/www/project/vendor/yiisoft/yii2/base/Module.php(740): yii\di\ServiceLocator->get('', '')
#12 /var/www/project/vendor/yiisoft/yii2/web/Application.php(178): yii\base\Module->get('', '')
#13 /var/www/project/vendor/yiisoft/yii2/web/User.php(661): yii\web\Application->getSession()
#14 /var/www/project/vendor/yiisoft/yii2/web/User.php(191): yii\web\User->renewAuthStatus()
#15 /var/www/project/vendor/yiisoft/yii2/web/User.php(336): yii\web\User->getIdentity('')
#16 /var/www/project/vendor/yiisoft/yii2/base/Component.php(139): yii\web\User->getIsGuest()
#17 /var/www/project/vendor/yiisoft/yii2/base/BaseObject.php(16): yii\base\Component->__get('')
#19 /var/www/project/vendor/yiisoft/yii2/di/ServiceLocator.php(146): yii\base\BaseObject->__get('')
#20 /var/www/project/vendor/yiisoft/yii2/di/ServiceLocator.php(77): yii\base\Component->__get('')
#21 /var/www/project/vendor/yiisoft/yii2/base/BaseObject.php(14): yii\di\ServiceLocator->__get('')
#22 /var/www/project/vendor/yiisoft/yii2/base/BaseObject.php(108): common\components\UrlManager->init()
#23 /var/www/project/vendor/yiisoft/yii2/di/Container.php(383): yii\base\BaseObject->__construct('')
#24 /var/www/project/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs('')
#25 /var/www/project/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('', '', '')
#26 /var/www/project/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('', '', '')
#27 /var/www/project/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject('', '')
#28 /var/www/project/vendor/yiisoft/yii2/base/Module.php(740): yii\di\ServiceLocator->get('', '')
#29 /var/www/project/vendor/yiisoft/yii2/di/ServiceLocator.php(74): yii\base\Module->get('', '')
#30 /var/www/project/vendor/yiisoft/yii2/base/Application.php(25): yii\di\ServiceLocator->__get('')
#32 /var/www/project/vendor/yiisoft/yii2/web/Application.php(69): yii\base\Application->bootstrap()
#33 /var/www/project/vendor/yiisoft/yii2/base/Application.php(273): yii\web\Application->bootstrap()
#34 /var/www/project/vendor/yiisoft/yii2/base/BaseObject.php(108): yii\base\Application->init()
#35 /var/www/project/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct('')
#36 /var/www/project/frontend/web/index.php(35): yii\base\Application->__construct('')
#37 {main}
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | dev-master
| PHP version      | 5.5
| Operating system | Ubuntu

### PR DESCRIPTION
**Pull request by samdark**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #15627

### CODE REVIEW

**Comment by samdark** [comment]
Now we have it working properly.

File: framework/web/Session.php [hunk 1]
```diff
@@ -935,10 +938,22 @@ protected function freeze()
...
+
+            if ($this->getIsActive()) {
+                Yii::info('Session unfrozen', __METHOD__);
+            } else {
+                $error = error_get_last();
+                $message = isset($error['message']) ? $error['message'] : 'Failed to unfreeze session.';
+                Yii::error($message, __METHOD__);
+            }
+
+            if ($this->frozenSessionData !== null) {
```
Comment (SilverFire) [inline framework/web/Session.php]: It seems that this condition is redundant. It is already wrapped with the same `if` condition and the code above does not change `frozenSessionData` variable, is it?

**Review by SilverFire — CHANGES_REQUESTED** [review]

**Review by SilverFire — APPROVED** [review]
