### PR TITLE
Fixed excess escaping in Command::batchInsert()

### LINKED ISSUE #11242: batchInsert incorrectly quotes SQL query with values, containing {{ }} symbols
### What steps will reproduce the problem?

`$this->db->createCommand()->batchInsert('table', ['column1'], [["input-{{value}}"]])->execute();`
### What is the expected result?

Value inserted into a table
### What do you get instead?

[yii\db\Exception] SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax
The SQL being executed was: `INSERT INTO "table" ("column1") VALUES ('input-"value"')`
### Additional info

The problem is that `Command::setSql` method quotes already prepared batch insert query with `'/(\\{\\{(%?[\w\-\. ]+%?)\\}\\}|\\[\\[([\w\-\. ]+)\\]\\])/'` regexp inside `Connection::quoteSql` which does not know anything about the context 

| Q | A |
| --- | --- |
| Yii version | Yii v2.0.7 |
| PHP version | PHP 5.6.16 (cli) (built: Nov 27 2015 10:28:34) |
| Operating system | Any |

### PR DESCRIPTION
**Pull request by SilverFire**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no. Read bellow
| Tests pass?   | hope so :)
| Fixed issues  | #11242

Fixes #11242

There is a test that contain a comment about a potentially wrong behavior. This behavior was NOT introduced in this PR, I've just covered it with a unit test.

### CODE REVIEW

**Comment by samdark** [comment]
Seems to fail important tests.

**Comment by SilverFire** [comment]
Fixed in master

**Comment by kidol** [comment]
There is name clash with `getRawSql()` method.

Also I think it would be better to first re-evaluated whether prepared statements can be used in regards to #12528

**Comment by samdark** [comment]
#12528 is now fixed. @SilverFire do you remember what's missing in this one?

**Comment by SilverFire** [comment]
> I think it would be better to first re-evaluated whether prepared statements can be used

Prepared statements are limited on number of placeholders, for instance MySQL has limit of 65535. Probably, we can calculate number of placeholders, split input data in buckets not to step over the limit and run multiple queries in transaction, but I think this way is neither easier nor better.



> do you remember what's missing in this one?

I think I would like to see @cebe input. I will resolve conflicts and prepare for merge.

File: framework/db/Command.php [hunk 1]
```diff
@@ -137,19 +137,43 @@ public function getSql()
...
     public function setSql($sql)
     {
         if ($sql !== $this->_sql) {
             $this->cancel();
+            $this->reset();
             $this->_sql = $this->db->quoteSql($sql);
-            $this->_pendingParams = [];
-            $this->params = [];
-            $this->_refreshTableName = null;
+        }
```
Comment (tom--) [inline framework/db/Command.php]: `$this->_sql` is the quoted version of `$sql`. So the condition `if ($sql !== $this->_sql)` doesn't test for changes.

Is this test really required?

File: framework/db/Command.php [hunk 2]
```diff
@@ -137,19 +137,43 @@ public function getSql()
...
+     * @see reset()
+     * @see cancel()
+     */
+    public function setRawSql($sql)
+    {
+        if ($sql !== $this->_sql) {
+            $this->cancel();
+            $this->reset();
+            $this->_sql = $sql;
         }
```
Comment (tom--) [inline framework/db/Command.php]: In this case the test is correct but all of the operations in the `if` branch (cancel, reset, assign) are very fast. Why not do these steps unconditionally?

File: framework/db/Command.php [hunk 3]
```diff
@@ -457,9 +481,16 @@ public function insert($table, $columns)
...
     {
+        $table = $this->db->quoteSql($table);
+        $columns = array_map(function ($column) {
+            return $this->db->quoteSql($column);
+        }, $columns);
+
         $sql = $this->db->getQueryBuilder()->batchInsert($table, $columns, $rows);
 
-        return $this->setSql($sql);
+        $this->setRawSql($sql);
```
Comment (tom--) [inline framework/db/Command.php]: The intermediate variable `$sql` does little work. But its value could be a very long string. Unless the PHP compiler does The Right Thing then it's fine. Otherwise it `$sql` could be eliminated.

**Review by tom-- — COMMENTED** [review]
Did you (or anyone) verify that the new tests fail in .12?

File: framework/db/Command.php (hunk 3 above)
Comment (tom--) [reply framework/db/Command.php]: I'm pretty sure it makes no difference so whatever style you prefer.

File: framework/db/Command.php (hunk 1 above)
Comment (cebe) [reply framework/db/Command.php]: it probably isn't as this check has been introduced before `quoteSql` has been created. This does not belong to this PR however. Changing it could probably break code in very rare cases.

File: framework/db/Command.php [hunk 4]
```diff
@@ -137,19 +137,43 @@ public function getSql()
...
+    }
+
+    /**
+     * Specifies the SQL statement to be executed. The SQL statement will not be modified in any way.
+     * The previous SQL execution (if any) will be cancelled, and [[params]] will be cleared as well. See [[reset()]]
+     * for details.
+     *
+     * @param string $sql the SQL statement to be set.
+     * @return $this
+     * @since 2.0.11
```
Comment (cebe) [inline framework/db/Command.php]: 2.0.13

File: framework/db/Command.php [hunk 5]
```diff
@@ -137,19 +137,43 @@ public function getSql()
...
+        return $this;
+    }
+
+    /**
+     * Specifies the SQL statement to be executed. The SQL statement will not be modified in any way.
+     * The previous SQL execution (if any) will be cancelled, and [[params]] will be cleared as well. See [[reset()]]
+     * for details.
+     *
+     * @param string $sql the SQL statement to be set.
+     * @return $this
```
Comment (cebe) [inline framework/db/Command.php]: `@return $this this command instance`

File: framework/db/Command.php (hunk 2 above)
Comment (cebe) [reply framework/db/Command.php]: there is no point in testing `$sql !== $this->_sql` here, I am for removing it.

File: framework/db/Command.php [hunk 6]
```diff
@@ -945,4 +976,18 @@ protected function refreshTableSchema()
             $this->db->getSchema()->refreshTableSchema($this->_refreshTableName);
         }
     }
+
+    /**
+     * Resets [[sql]] and [[params]] properties.
+     *
+     * @void
+     * @since 2.0.11
```
Comment (cebe) [inline framework/db/Command.php]: remove `@void`
`@since 2.0.13`

File: framework/CHANGELOG.md [hunk 7]
```diff
@@ -36,6 +36,7 @@ Yii Framework 2 Change Log
 - Bug #13159: Fixed `destroy` method in `yii.captcha.js` which did not work as expected (arogachev)
 - Bug #13198: Fixed order of checks in `yii\validators\IpValidator` that sometimes caused wrong error message (silverfire)
 - Bug #13200: Creating Urls for routes specified in `yii\rest\UrlRule::$extraPatterns` did not work if no HTTP verb was specified (cebe)
+- Bug #11242: Fixed excess escaping in `yii\db\Command::batchInsert()` (silverfire)
```
Comment (cebe) [inline framework/CHANGELOG.md]: rebase and move the changelog entry.

**Review by cebe — CHANGES_REQUESTED** [review]
minor change required. solution looks good to me.

File: framework/CHANGELOG.md [hunk 8]
```diff
@@ -271,6 +272,8 @@ Yii Framework 2 Change Log
 - Bug #13128: Fixed incorrect position of {pos} string in ColumnSchemaBuilder `__toString` (df2)
 - Bug #13159: Fixed `destroy` method in `yii.captcha.js` which did not work as expected (arogachev)
 - Bug #13198: Fixed order of checks in `yii\validators\IpValidator` that sometimes caused wrong error message (silverfire)
+- Bug #13200: Creating Urls for routes specified in `yii\rest\UrlRule::$extraPatterns` did not work if no HTTP verb was specified (cebe)
```
Comment (samdark) [inline framework/CHANGELOG.md]: I don't think these should be here.

File: framework/db/Command.php [hunk 9]
```diff
@@ -137,19 +137,43 @@ public function getSql()
     }
 
     /**
-     * Specifies the SQL statement to be executed.
-     * The previous SQL execution (if any) will be cancelled, and [[params]] will be cleared as well.
+     * Specifies the SQL statement to be executed. The SQL statement will be quoted using [[Connection::quoteSql()]].
+     * The previous SQL execution (if any) will be cancelled, and [[params]] will be cleared as well. See [[reset()]]
```
Comment (samdark) [inline framework/db/Command.php]: `The previous SQL execution (if any) will be cancelled` → `The previous SQL (if any) will be discarded`

File: framework/db/Command.php [hunk 10]
```diff
@@ -137,19 +137,43 @@ public function getSql()
...
-            $this->params = [];
-            $this->_refreshTableName = null;
+        }
+
+        return $this;
+    }
+
+    /**
+     * Specifies the SQL statement to be executed. The SQL statement will not be modified in any way.
+     * The previous SQL execution (if any) will be cancelled, and [[params]] will be cleared as well. See [[reset()]]
```
Comment (samdark) [inline framework/db/Command.php]: `The previous SQL execution (if any) will be cancelled` → `The previous SQL (if any) will be discarded`

**Review by samdark — APPROVED** [review]
Good to merge except messed up changelog and a few phpdoc corrections.

File: framework/CHANGELOG.md (hunk 8 above)
Comment (SilverFire) [reply framework/CHANGELOG.md]: It's not the first time when `git merge` messes up changelog :(

**Comment by sokrat** [comment]
This changes has broken ```batchInsert()``` with table name contains special characters.
https://github.com/yiisoft/yii2/blob/75dbdb008363b90d4ffc8f502022763aedd6998a/framework/db/Command.php#L488
```
var_dump(Yii::$app->db->quoteSql('{{%test}}'));
""test""
```

**Comment by cebe** [comment]
@sokrat please open a new issue and give more details about the problem.
